d /run/aiden 0755 root root -
d /run/audio_service 0755 root root -
d /run/ble_service 0755 root root -
d /run/frame_service 0755 root root -
d /var/log/adb 0755 root root -
d /var/log/audio_service 0755 root root -
d /var/log/ble_service 0755 root root -
d /var/log/frame_service 0755 root root -
d /var/log/ota 0755 root root -
