interface=usb0
bind-interfaces
except-interface=wlan0
except-interface=lo
port=0
no-resolv
no-hosts
dhcp-range=192.168.42.100,192.168.42.200,255.255.255.0,12h
dhcp-authoritative
dhcp-option=option:router
dhcp-option=option:dns-server
dhcp-leasefile=/run/aiden/dnsmasq-usb0.leases
log-dhcp
