#!/bin/sh
set -eu

TTYD_BIN=${TTYD_BIN:-${WETTY_BIN:-/oem/usr/bin/ttyd}}
TTYD_INTERFACE=${TTYD_INTERFACE:-${WETTY_HOST:-}}
TTYD_PORT=${TTYD_PORT:-${WETTY_PORT:-3000}}
TTYD_BASE=${TTYD_BASE:-${WETTY_BASE:-/webtty/}}
TTYD_TITLE=${TTYD_TITLE:-${WETTY_TITLE:-Aiden Shell}}
TTYD_COMMAND=${TTYD_COMMAND:-${WETTY_COMMAND:-/bin/login}}
TTYD_RENDERER=${TTYD_RENDERER:-${WETTY_RENDERER:-canvas}}
TTYD_FONT_SIZE=${TTYD_FONT_SIZE:-${WETTY_FONT_SIZE:-24}}
TTYD_SCROLLBACK=${TTYD_SCROLLBACK:-${WETTY_SCROLLBACK:-500}}
TTYD_CURSOR_STYLE=${TTYD_CURSOR_STYLE:-${WETTY_CURSOR_STYLE:-bar}}
TTYD_DISABLE_RESIZE_OVERLAY=${TTYD_DISABLE_RESIZE_OVERLAY:-${WETTY_DISABLE_RESIZE_OVERLAY:-true}}
TTYD_MAX_CLIENTS=${TTYD_MAX_CLIENTS:-${WETTY_MAX_CLIENTS:-2}}

set -- \
    --port "${TTYD_PORT}" \
    --base-path "${TTYD_BASE}" \
    --max-clients "${TTYD_MAX_CLIENTS}" \
    --client-option "titleFixed=${TTYD_TITLE}" \
    --client-option "rendererType=${TTYD_RENDERER}" \
    --client-option "fontSize=${TTYD_FONT_SIZE}" \
    --client-option "scrollback=${TTYD_SCROLLBACK}" \
    --client-option "cursorStyle=${TTYD_CURSOR_STYLE}" \
    --client-option "disableResizeOverlay=${TTYD_DISABLE_RESIZE_OVERLAY}"
if [ -n "${TTYD_INTERFACE}" ]; then
    set -- "$@" --interface "${TTYD_INTERFACE}"
fi
set -- "$@" "${TTYD_COMMAND}"

exec "${TTYD_BIN}" "$@"
