[Unit]
Requires=aiden-bluetooth-attach.service aiden-bluetooth-state.service
After=aiden-bluetooth-attach.service aiden-bluetooth-state.service
StartLimitIntervalSec=60s
StartLimitBurst=5

[Service]
Restart=on-failure
RestartSec=2s
