FRAME_SERVICE_BIN=/oem/usr/bin/frame_service
SOCKET_PATH=/run/frame_service/frame_service.sock
FRAME_SERVICE_FPS=30
FRAME_SERVICE_WIDTH=1920
FRAME_SERVICE_HEIGHT=1080
FRAME_SERVICE_FORCE_TRIGGER=auto
FRAME_SERVICE_SUBDEV=
FRAME_SERVICE_EDID=auto
FRAME_SERVICE_TC358743_EDID=/oem/usr/share/aiden/edid/hdmi_1080p30_cta.hex
FRAME_SERVICE_TC358743_HPD_LOW_SECONDS=2
FRAME_SERVICE_TC358743_SETTLE_SECONDS=5
LOG_PATH=/var/log/frame_service/frame_service.log
