package mnk

// ADB Android keycode aliases
// Maps common key names to Android KEYCODE_* constants
var adbAndroidKeycodeAliases = map[string]string{
	"android_back":              "KEYCODE_BACK",
	"back":                      "KEYCODE_BACK",
	"keycode_back":              "KEYCODE_BACK",
	"android_home":              "KEYCODE_HOME",
	"keycode_home":              "KEYCODE_HOME",
	"menu":                      "KEYCODE_MENU",
	"keycode_menu":              "KEYCODE_MENU",
	"search":                    "KEYCODE_SEARCH",
	"keycode_search":            "KEYCODE_SEARCH",
	"power":                     "KEYCODE_POWER",
	"keycode_power":             "KEYCODE_POWER",
	"sleep":                     "KEYCODE_SLEEP",
	"keycode_sleep":             "KEYCODE_SLEEP",
	"volume_mute":               "KEYCODE_VOLUME_MUTE",
	"keycode_volume_mute":       "KEYCODE_VOLUME_MUTE",
	"volumeup":                  "KEYCODE_VOLUME_UP",
	"volume_up":                 "KEYCODE_VOLUME_UP",
	"keycode_volume_up":         "KEYCODE_VOLUME_UP",
	"volumedown":                "KEYCODE_VOLUME_DOWN",
	"volume_down":               "KEYCODE_VOLUME_DOWN",
	"keycode_volume_down":       "KEYCODE_VOLUME_DOWN",
	"media_fast_forward":        "KEYCODE_MEDIA_FAST_FORWARD",
	"media_rewind":              "KEYCODE_MEDIA_REWIND",
	"media_next":                "KEYCODE_MEDIA_NEXT",
	"media_previous":            "KEYCODE_MEDIA_PREVIOUS",
	"media_stop":                "KEYCODE_MEDIA_STOP",
	"media_play_pause":          "KEYCODE_MEDIA_PLAY_PAUSE",
	"app_switch":                "KEYCODE_APP_SWITCH",
	"keycode_app_switch":        "KEYCODE_APP_SWITCH",
	"recents":                   "KEYCODE_APP_SWITCH",
	"return":                    "KEYCODE_ENTER",
	"send":                      "KEYCODE_ENTER",
	"delete_backward":           "KEYCODE_DEL",
	"backward_delete":           "KEYCODE_DEL",
	"move_home":                 "KEYCODE_MOVE_HOME",
	"keyboard_home":             "KEYCODE_MOVE_HOME",
	"screenshot":                "KEYCODE_SYSRQ",
	"key_usage_screenshot":      "KEYCODE_SYSRQ",
	"brightness_up":             "KEYCODE_BRIGHTNESS_UP",
	"key_usage_brightness_up":   "KEYCODE_BRIGHTNESS_UP",
	"brightness_down":           "KEYCODE_BRIGHTNESS_DOWN",
	"key_usage_brightness_down": "KEYCODE_BRIGHTNESS_DOWN",
	"refresh":                   "KEYCODE_REFRESH",
	"key_usage_refresh":         "KEYCODE_REFRESH",
	"settings":                  "KEYCODE_SETTINGS",
	"key_usage_settings":        "KEYCODE_SETTINGS",
	"language_switch":           "KEYCODE_LANGUAGE_SWITCH",
	"key_usage_language_switch": "KEYCODE_LANGUAGE_SWITCH",
}

// Standard keyboard keycode map for ADB
var adbKeyboardKeycodeMap = map[string]string{
	// Letters
	"a": "KEYCODE_A", "b": "KEYCODE_B", "c": "KEYCODE_C", "d": "KEYCODE_D",
	"e": "KEYCODE_E", "f": "KEYCODE_F", "g": "KEYCODE_G", "h": "KEYCODE_H",
	"i": "KEYCODE_I", "j": "KEYCODE_J", "k": "KEYCODE_K", "l": "KEYCODE_L",
	"m": "KEYCODE_M", "n": "KEYCODE_N", "o": "KEYCODE_O", "p": "KEYCODE_P",
	"q": "KEYCODE_Q", "r": "KEYCODE_R", "s": "KEYCODE_S", "t": "KEYCODE_T",
	"u": "KEYCODE_U", "v": "KEYCODE_V", "w": "KEYCODE_W", "x": "KEYCODE_X",
	"y": "KEYCODE_Y", "z": "KEYCODE_Z",

	// Numbers
	"0": "KEYCODE_0", "1": "KEYCODE_1", "2": "KEYCODE_2", "3": "KEYCODE_3",
	"4": "KEYCODE_4", "5": "KEYCODE_5", "6": "KEYCODE_6", "7": "KEYCODE_7",
	"8": "KEYCODE_8", "9": "KEYCODE_9",

	// Modifiers
	"ctrl":   "KEYCODE_CTRL_LEFT",
	"lctrl":  "KEYCODE_CTRL_LEFT",
	"rctrl":  "KEYCODE_CTRL_RIGHT",
	"shift":  "KEYCODE_SHIFT_LEFT",
	"lshift": "KEYCODE_SHIFT_LEFT",
	"rshift": "KEYCODE_SHIFT_RIGHT",
	"alt":    "KEYCODE_ALT_LEFT",
	"lalt":   "KEYCODE_ALT_LEFT",
	"ralt":   "KEYCODE_ALT_RIGHT",
	"meta":   "KEYCODE_META_LEFT",
	"lmeta":  "KEYCODE_META_LEFT",
	"rmeta":  "KEYCODE_META_RIGHT",
	"super":  "KEYCODE_META_LEFT",
	"win":    "KEYCODE_META_LEFT",
	"cmd":    "KEYCODE_META_LEFT",

	// Edit keys
	"enter":     "KEYCODE_ENTER",
	"backspace": "KEYCODE_DEL",
	"delete":    "KEYCODE_FORWARD_DEL",
	"tab":       "KEYCODE_TAB",
	"space":     "KEYCODE_SPACE",
	"esc":       "KEYCODE_ESCAPE",
	"escape":    "KEYCODE_ESCAPE",

	// Navigation
	"up":       "KEYCODE_DPAD_UP",
	"down":     "KEYCODE_DPAD_DOWN",
	"left":     "KEYCODE_DPAD_LEFT",
	"right":    "KEYCODE_DPAD_RIGHT",
	"pageup":   "KEYCODE_PAGE_UP",
	"pagedown": "KEYCODE_PAGE_DOWN",
	"home":     "KEYCODE_MOVE_HOME",
	"end":      "KEYCODE_MOVE_END",

	// Function keys
	"f1":  "KEYCODE_F1",
	"f2":  "KEYCODE_F2",
	"f3":  "KEYCODE_F3",
	"f4":  "KEYCODE_F4",
	"f5":  "KEYCODE_F5",
	"f6":  "KEYCODE_F6",
	"f7":  "KEYCODE_F7",
	"f8":  "KEYCODE_F8",
	"f9":  "KEYCODE_F9",
	"f10": "KEYCODE_F10",
	"f11": "KEYCODE_F11",
	"f12": "KEYCODE_F12",

	// Punctuation
	"minus":      "KEYCODE_MINUS",
	"equal":      "KEYCODE_EQUALS",
	"leftbrace":  "KEYCODE_LEFT_BRACKET",
	"rightbrace": "KEYCODE_RIGHT_BRACKET",
	"backslash":  "KEYCODE_BACKSLASH",
	"semicolon":  "KEYCODE_SEMICOLON",
	"apostrophe": "KEYCODE_APOSTROPHE",
	"grave":      "KEYCODE_GRAVE",
	"comma":      "KEYCODE_COMMA",
	"dot":        "KEYCODE_PERIOD",
	"period":     "KEYCODE_PERIOD",
	"slash":      "KEYCODE_SLASH",

	// Other
	"capslock":    "KEYCODE_CAPS_LOCK",
	"insert":      "KEYCODE_INSERT",
	"printscreen": "KEYCODE_SYSRQ",
	"scrolllock":  "KEYCODE_SCROLL_LOCK",
	"pause":       "KEYCODE_BREAK",
}
