#pragma once

// Standalone viewer for the agent's raw LLM HTTP logs. Served at GET /llm-logs.
// It reads JSONL files via /api/llm-logs and /api/llm-logs/file/<name>, pairs
// each request with the response that immediately follows it, renders the
// request `messages` array in full, and offers an inline git-style diff of a
// request's messages against the previous request.
static const char* CONFIG_WEB_LLM_HTML =
    "<!DOCTYPE html>\n"
    "<html lang=\"en\">\n"
    "<head>\n"
    "  <meta charset=\"UTF-8\">\n"
    "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
    "  <title>Aiden LLM Logs</title>\n"
    "  <style>\n"
    "    *{box-sizing:border-box}body{margin:0;background:#f9fafb;color:#111827;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif}\n"
    "    .topbar{display:flex;align-items:center;gap:12px;padding:14px 20px;background:#fff;border-bottom:1px solid #e5e7eb}\n"
    "    .topbar h1{margin:0;font-size:18px}.topbar a{color:#2563eb;text-decoration:none;font-size:14px}.topbar a:hover{text-decoration:underline}\n"
    "    .layout{display:flex;height:calc(100vh - 53px)}\n"
    "    .sidebar{flex:0 0 280px;border-right:1px solid #e5e7eb;background:#fff;overflow-y:auto}\n"
    "    .sidebar-head{display:flex;align-items:center;justify-content:space-between;padding:12px 14px;border-bottom:1px solid #f0f1f4}\n"
    "    .sidebar-head .button{padding:5px 10px;font-size:12px}\n"
    "    .file-row{display:block;width:100%;border:0;border-bottom:1px solid #f0f1f4;background:transparent;text-align:left;padding:10px 14px;cursor:pointer;font:inherit;color:#111827}\n"
    "    .file-row:hover{background:#f9fafb}.file-row.active{background:#eff6ff}\n"
    "    .file-name{font-size:13px;font-weight:600;word-break:break-all}.file-meta{font-size:11px;color:#6b7280;margin-top:2px}\n"
    "    .detail{flex:1;display:flex;overflow:hidden}\n"
    "    .request-list{flex:0 0 360px;border-right:1px solid #e5e7eb;background:#fff;display:flex;flex-direction:column;overflow:hidden}\n"
    "    .request-detail{flex:1;display:flex;flex-direction:column;overflow:hidden;background:#f9fafb}\n"
    "    .request-list-head,.request-detail-head{padding:12px 14px;border-bottom:1px solid #e5e7eb;font-size:13px;font-weight:600;color:#111827;background:#f9fafb}\n"
    "    #requestList,#requestDetail{flex:1;overflow-y:auto}\n"
    "    .request-item{display:block;width:100%;border:0;border-bottom:1px solid #f0f1f4;background:transparent;text-align:left;padding:12px 14px;cursor:pointer;font:inherit;color:#111827}\n"
    "    .request-item:hover{background:#f9fafb}.request-item.active{background:#eff6ff;border-left:3px solid #2563eb}\n"
    "    .request-item-head{display:flex;align-items:center;gap:8px;margin-bottom:6px}\n"
    "    .request-item-index{font-size:12px;font-weight:700;color:#6b7280}\n"
    "    .request-item-preview{font-size:13px;color:#111827;overflow:hidden;text-overflow:ellipsis;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;line-height:1.4}\n"
    "    .empty{color:#6b7280;font-size:14px;padding:24px 0}\n"
    "    .group{border:1px solid #e5e7eb;border-radius:12px;background:#fff;margin-bottom:16px;overflow:hidden}\n"
    "    .group-head{display:flex;align-items:center;gap:10px;padding:10px 14px;background:#f3f4f6;border-bottom:1px solid #e5e7eb;flex-wrap:wrap}\n"
    "    .group-title{font-size:14px;font-weight:700}\n"
    "    .badge{font-size:12px;padding:2px 8px;border-radius:999px;font-weight:600}\n"
    "    .badge.ok{background:#dcfce7;color:#166534}.badge.err{background:#fee2e2;color:#991b1b}.badge.none{background:#fef3c7;color:#92400e}\n"
    "    .group-actions{margin-left:auto;display:flex;gap:8px}\n"
    "    .button{border:0;border-radius:8px;padding:6px 12px;font-size:13px;font-weight:600;cursor:pointer;background:#f3f4f6;color:#111827}\n"
    "    .button.primary{background:#2563eb;color:#fff}.button.active{background:#2563eb;color:#fff}.button:hover{opacity:.9}\n"
    "    .group-body{padding:12px 14px}\n"
    "    .msg{border:1px solid #e5e7eb;border-radius:8px;margin-bottom:10px;overflow:hidden}\n"
    "    .msg-head,.diff-msg-head{display:flex;align-items:center;gap:6px;padding:6px 10px;background:#f9fafb;border-bottom:1px solid #f0f1f4;font-size:12px;line-height:1.2;font-weight:700;text-transform:uppercase;letter-spacing:.03em;color:#374151}\n"
    "    .msg-index{font-variant-numeric:tabular-nums;color:#6b7280}\n"
    "    .msg-role,.diff-mark{min-width:0}\n"
    "    .msg-head-action{margin-left:auto;display:flex;align-items:center}\n"
    "    .msg-collapse{width:22px;height:22px;border:1px solid #d1d5db;border-radius:6px;background:#fff;color:#374151;cursor:pointer;font-size:13px;line-height:1;display:inline-flex;align-items:center;justify-content:center}\n"
    "    .msg-collapse:hover{background:#f3f4f6}\n"
    "    .role-system{color:#7c3aed}.role-user{color:#2563eb}.role-assistant{color:#059669}.role-tool{color:#b45309}\n"
    "    .msg-content{padding:8px 10px;white-space:pre-wrap;word-break:break-word;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:12.5px;line-height:1.5}\n"
    "    .msg-content.collapsed{max-height:10em;overflow:hidden;position:relative}\n"
    "    .msg-content.collapsed::after{content:'';position:absolute;bottom:0;left:0;right:0;height:3em;background:linear-gradient(transparent,#fff)}\n"
    "    .msg-part{margin:0 0 8px}.msg-part:last-child{margin-bottom:0}.msg-text{white-space:pre-wrap;word-break:break-word}\n"
    "    .msg-image{display:block;max-width:100%;max-height:460px;object-fit:contain;border:1px solid #d1d5db;border-radius:6px;background:#111827}\n"
    "    .msg-image-meta{margin-top:4px;color:#6b7280;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;font-size:11px;line-height:1.3;text-transform:none;letter-spacing:0}\n"
    "    .diff-stats{display:flex;gap:12px;font-size:12px;align-items:center}\n"
    "    .diff-stat{display:flex;align-items:center;gap:4px}\n"
    "    .diff-stat .icon{width:16px;height:16px;border-radius:3px;display:inline-flex;align-items:center;justify-content:center;font-size:11px;font-weight:700}\n"
    "    .diff-stat.added .icon{background:#dcfce7;color:#166534}\n"
    "    .diff-stat.removed .icon{background:#fee2e2;color:#991b1b}\n"
    "    .diff-stat.modified .icon{background:#dbeafe;color:#1e40af}\n"
    "    .tool-call{margin-top:8px;border-top:1px dashed #e5e7eb;padding-top:8px}\n"
    "    .tool-call .tc-name{font-weight:700;color:#b45309;font-size:12.5px}\n"
    "    .diff-line{border-left:3px solid transparent}\n"
    "    .diff-line.collapsed::after{background:linear-gradient(transparent,#fff)}\n"
    "    .diff-line.collapsed.diff-add::after{background:linear-gradient(transparent,#ecfdf5)}\n"
    "    .diff-line.collapsed.diff-del::after{background:linear-gradient(transparent,#fef2f2)}\n"
    "    .diff-add{background:#ecfdf5;border-left-color:#059669}\n"
    "    .diff-del{background:#fef2f2;border-left-color:#dc2626;color:#7f1d1d}\n"
    "    .diff-same{color:#6b7280}\n"
    "    .diff-msg{margin-bottom:10px;border:1px solid #e5e7eb;border-radius:8px;overflow:hidden}\n"
    "    .diff-msg.added .diff-msg-head{background:#ecfdf5;color:#166534}\n"
    "    .diff-msg.removed .diff-msg-head{background:#fef2f2;color:#991b1b}\n"
    "    .raw-toggle{font-size:12px;color:#6b7280;cursor:pointer;text-decoration:underline;margin-top:8px;display:inline-block}\n"
    "    pre.raw{white-space:pre-wrap;word-break:break-word;background:#0b1021;color:#d6e2ff;padding:10px;border-radius:8px;font-size:12px;overflow-x:auto}\n"
    "    .response-section{margin-top:18px;padding-top:14px;border-top:2px solid #e5e7eb}\n"
    "    .response-section-head{display:flex;align-items:center;gap:10px;margin-bottom:10px;font-size:13px;font-weight:700;color:#111827}\n"
    "  </style>\n"
    "</head>\n"
    "<body>\n"
    "  <div class=\"topbar\">\n"
    "    <a href=\"/\">\xe2\x86\x90 Back to Config</a>\n"
    "    <h1>LLM HTTP Logs</h1>\n"
    "  </div>\n"
    "  <div class=\"layout\">\n"
    "    <div class=\"sidebar\">\n"
    "      <div class=\"sidebar-head\">\n"
    "        <span style=\"font-size:13px;font-weight:600\">Log Files</span>\n"
    "        <button class=\"button\" onclick=\"loadFileList()\">Refresh</button>\n"
    "      </div>\n"
    "      <div id=\"fileList\"></div>\n"
    "    </div>\n"
    "    <div class=\"detail\">\n"
    "      <div class=\"request-list\">\n"
    "        <div class=\"request-list-head\">Requests</div>\n"
    "        <div id=\"requestList\">\n"
    "          <div class=\"empty\" style=\"padding:12px\">Select a log file to view requests.</div>\n"
    "        </div>\n"
    "      </div>\n"
    "      <div class=\"request-detail\">\n"
    "        <div class=\"request-detail-head\">Request Detail</div>\n"
    "        <div id=\"requestDetail\" style=\"padding:18px 20px\">\n"
    "          <div class=\"empty\">Select a request to view details.</div>\n"
    "        </div>\n"
    "      </div>\n"
    "    </div>\n"
    "  </div>\n"
    "  <script>\n"
    "let state = {files: [], selectedFile: null, groups: [], selectedRequest: null};\n"
    "async function request(url) {\n"
    "  const res = await fetch(url);\n"
    "  const text = await res.text();\n"
    "  let body = {};\n"
    "  try { body = text ? JSON.parse(text) : {}; } catch(err) { body = {ok: false, error: text || err.message}; }\n"
    "  if (!res.ok) throw new Error(body.error || ('HTTP ' + res.status));\n"
    "  return body;\n"
    "}\n"
    "async function loadFileList() {\n"
    "  try {\n"
    "    const data = await request('/api/llm-logs');\n"
    "    state.files = data.files || [];\n"
    "    renderFileList();\n"
    "    if (state.files.length > 0 && !state.selectedFile) {\n"
    "      loadFile(0);\n"
    "    }\n"
    "  } catch(err) {\n"
    "    document.getElementById('fileList').innerHTML = '<div class=\"empty\" style=\"padding:12px\">Failed to load: ' + esc(err.message) + '</div>';\n"
    "  }\n"
    "}\n"
    "function renderFileList() {\n"
    "  const el = document.getElementById('fileList');\n"
    "  if (state.files.length === 0) {\n"
    "    el.innerHTML = '<div class=\"empty\" style=\"padding:12px\">No log files available.</div>';\n"
    "    return;\n"
    "  }\n"
    "  el.innerHTML = state.files.map((f, i) => {\n"
    "    const active = state.selectedFile && state.selectedFile.name === f.name ? ' active' : '';\n"
    "    const kb = Math.round((f.size_bytes || 0) / 1024);\n"
    "    return '<button class=\"file-row' + active + '\" onclick=\"loadFile(' + i + ')\">' +\n"
    "           '<div class=\"file-name\">' + esc(f.name) + '</div>' +\n"
    "           '<div class=\"file-meta\">' + kb + ' KB</div>' +\n"
    "           '</button>';\n"
    "  }).join('');\n"
    "}\n"
    "async function loadFile(index) {\n"
    "  const f = state.files[index];\n"
    "  if (!f) return;\n"
    "  state.selectedFile = f;\n"
    "  state.selectedRequest = null;\n"
    "  renderFileList();\n"
    "  document.getElementById('requestList').innerHTML = '<div class=\"empty\" style=\"padding:12px\">Loading...</div>';\n"
    "  document.getElementById('requestDetail').innerHTML = '<div class=\"empty\">Select a request to view details.</div>';\n"
    "  try {\n"
    "    const data = await request('/api/llm-logs/file/' + encodeURIComponent(f.name));\n"
    "    const lines = (data.content || '').trim().split('\\n').filter(l => l);\n"
    "    const entries = [];\n"
    "    for (let i = 0; i < lines.length; i++) {\n"
    "      try { entries.push(JSON.parse(lines[i])); } catch(e) {}\n"
    "    }\n"
    "    state.groups = groupEntries(entries);\n"
    "    renderGroups();\n"
    "  } catch(err) {\n"
    "    document.getElementById('requestList').innerHTML = '<div class=\"empty\" style=\"padding:12px\">Failed to load: ' + esc(err.message) + '</div>';\n"
    "  }\n"
    "}\n"
    "function groupEntries(entries) {\n"
    "  const groups = [];\n"
    "  for (let i = 0; i < entries.length; i++) {\n"
    "    const e = entries[i];\n"
    "    if (e.kind !== 'request') continue;\n"
    "    const g = {request: e, response: null};\n"
    "    if (i + 1 < entries.length && entries[i + 1].kind === 'response') {\n"
    "      g.response = entries[i + 1];\n"
    "      i++;\n"
    "    }\n"
    "    groups.push(g);\n"
    "  }\n"
    "  return groups;\n"
    "}\n"
    "function renderGroups() {\n"
    "  const listEl = document.getElementById('requestList');\n"
    "  const detailEl = document.getElementById('requestDetail');\n"
    "  if (state.groups.length === 0) {\n"
    "    listEl.innerHTML = '<div class=\"empty\" style=\"padding:12px\">No valid requests in this file.</div>';\n"
    "    detailEl.innerHTML = '<div class=\"empty\">Select a request to view details.</div>';\n"
    "    return;\n"
    "  }\n"
    "  listEl.innerHTML = state.groups.map((g, i) => renderRequestItem(g, i)).join('');\n"
    "  if (state.selectedRequest === null) {\n"
    "    state.selectedRequest = 0;\n"
    "  }\n"
    "  renderRequestDetail();\n"
    "}\n"
    "function renderRequestItem(g, idx) {\n"
    "  const req = parseBody(g.request.body);\n"
    "  const messages = req.messages || [];\n"
    "  const lastMsg = messages.length > 0 ? messages[messages.length - 1] : null;\n"
    "  const preview = lastMsg ? (messageText(lastMsg) || JSON.stringify(lastMsg).substring(0, 100)) : 'No message content';\n"
    "  const status = !g.response ? 'none' : (g.response.status >= 200 && g.response.status < 300 ? 'ok' : 'err');\n"
    "  const badgeText = !g.response ? 'No Response' : (status === 'ok' ? g.response.status : 'Error ' + g.response.status);\n"
    "  const badgeClass = 'badge ' + status;\n"
    "  const active = state.selectedRequest === idx ? ' active' : '';\n"
    "  let html = '<button class=\"request-item' + active + '\" onclick=\"selectRequest(' + idx + ')\">';\n"
    "  html += '<div class=\"request-item-head\">';\n"
    "  html += '<span class=\"request-item-index\">#' + (idx + 1) + '</span>';\n"
    "  html += '<span class=\"' + badgeClass + '\">' + esc(badgeText) + '</span>';\n"
    "  html += '<span style=\"font-size:11px;color:#9ca3af;margin-left:auto\">' + esc(g.request.ts.substring(11, 19)) + '</span>';\n"
    "  html += '</div>';\n"
    "  html += '<div class=\"request-item-preview\">' + esc(preview) + '</div>';\n"
    "  html += '</button>';\n"
    "  return html;\n"
    "}\n"
    "function selectRequest(idx) {\n"
    "  state.selectedRequest = idx;\n"
    "  renderGroups();\n"
    "}\n"
    "function renderRequestDetail() {\n"
    "  const detailEl = document.getElementById('requestDetail');\n"
    "  if (state.selectedRequest === null || !state.groups[state.selectedRequest]) {\n"
    "    detailEl.innerHTML = '<div class=\"empty\">Select a request to view details.</div>';\n"
    "    return;\n"
    "  }\n"
    "  const idx = state.selectedRequest;\n"
    "  const g = state.groups[idx];\n"
    "  const req = parseBody(g.request.body);\n"
    "  const status = !g.response ? 'none' : (g.response.status >= 200 && g.response.status < 300 ? 'ok' : 'err');\n"
    "  const badgeText = !g.response ? 'No Response' : (status === 'ok' ? g.response.status : 'Error ' + g.response.status);\n"
    "  const badgeClass = 'badge ' + status;\n"
    "  let html = '<div class=\"group\">';\n"
    "  html += '<div class=\"group-head\">';\n"
    "  html += '<span class=\"group-title\">Request #' + (idx + 1) + '</span>';\n"
    "  html += '<span class=\"' + badgeClass + '\">' + esc(badgeText) + '</span>';\n"
    "  html += '<span style=\"font-size:12px;color:#6b7280\">' + esc(g.request.ts) + '</span>';\n"
    "  if (idx > 0) {\n"
    "    const prevReq = parseBody(state.groups[idx - 1].request.body);\n"
    "    const diffStats = computeDiffStats(prevReq.messages || [], req.messages || []);\n"
    "    html += '<div class=\"diff-stats\">';\n"
    "    if (diffStats.added > 0) html += '<div class=\"diff-stat added\"><span class=\"icon\">+</span><span>' + diffStats.added + '</span></div>';\n"
    "    if (diffStats.removed > 0) html += '<div class=\"diff-stat removed\"><span class=\"icon\">-</span><span>' + diffStats.removed + '</span></div>';\n"
    "    if (diffStats.modified > 0) html += '<div class=\"diff-stat modified\"><span class=\"icon\">~</span><span>' + diffStats.modified + '</span></div>';\n"
    "    html += '</div>';\n"
    "  }\n"
    "  html += '<div class=\"group-actions\">';\n"
    "  html += '<button class=\"button\" id=\"msg-btn\" onclick=\"showDetailView(\\'messages\\')\">Messages</button>';\n"
    "  if (idx > 0) {\n"
    "    html += '<button class=\"button active\" id=\"diff-btn\" onclick=\"showDetailView(\\'diff\\')\">Diff</button>';\n"
    "  }\n"
    "  html += '<button class=\"button\" id=\"raw-btn\" onclick=\"showDetailView(\\'raw\\')\">Raw</button>';\n"
    "  html += '</div></div>';\n"
    "  const bodyContent = idx > 0 ? (function() {\n"
    "    const prevReq = parseBody(state.groups[idx - 1].request.body);\n"
    "    return renderDiff(prevReq.messages || [], req.messages || []);\n"
    "  })() : renderMessagesView(g, req);\n"
    "  html += '<div class=\"group-body\" id=\"detail-body\">' + bodyContent + '</div>';\n"
    "  html += '</div>';\n"
    "  detailEl.innerHTML = html;\n"
    "}\n"
    "function showDetailView(view) {\n"
    "  const idx = state.selectedRequest;\n"
    "  if (idx === null) return;\n"
    "  const g = state.groups[idx];\n"
    "  if (!g) return;\n"
    "  document.getElementById('msg-btn').className = view === 'messages' ? 'button active' : 'button';\n"
    "  const diffBtn = document.getElementById('diff-btn');\n"
    "  if (diffBtn) diffBtn.className = view === 'diff' ? 'button active' : 'button';\n"
    "  document.getElementById('raw-btn').className = view === 'raw' ? 'button active' : 'button';\n"
    "  const body = document.getElementById('detail-body');\n"
    "  const req = parseBody(g.request.body);\n"
    "  if (view === 'messages') {\n"
    "    body.innerHTML = renderMessagesView(g, req);\n"
    "  } else if (view === 'diff' && idx > 0) {\n"
    "    const prevReq = parseBody(state.groups[idx - 1].request.body);\n"
    "    body.innerHTML = renderDiff(prevReq.messages || [], req.messages || []);\n"
    "  } else if (view === 'raw') {\n"
    "    body.innerHTML = '<pre class=\"raw\">' + esc(JSON.stringify(req, null, 2)) + '</pre>';\n"
    "  }\n"
    "}\n"
    "function renderMessages(msgs, showIndex, idPrefix) {\n"
    "  showIndex = showIndex !== false;\n"
    "  idPrefix = idPrefix || 'msg';\n"
    "  if (!msgs || msgs.length === 0) return '<div style=\"color:#6b7280;font-size:13px\">No messages.</div>';\n"
    "  return msgs.map((m, i) => {\n"
    "    const uid = idPrefix + '-' + i;\n"
    "    let html = '<div class=\"msg\">';\n"
    "    const contentText = messageText(m);\n"
    "    const needsCollapse = messageNeedsCollapse(contentText);\n"
    "    html += renderMessageHead('msg-head role-' + cssToken(m.role || 'unknown'), m.role, showIndex ? i : null, '', needsCollapse ? uid : null);\n"
    "    html += '<div class=\"msg-content' + (needsCollapse ? ' collapsed' : '') + '\" id=\"' + uid + '\">';\n"
    "    html += renderMessageContent(m);\n"
    "    if (m.tool_calls && m.tool_calls.length > 0) {\n"
    "      html += m.tool_calls.map(tc => {\n"
    "        const fn = (tc && tc.function) || {};\n"
    "        const rawArgs = fn.arguments == null ? '' : fn.arguments;\n"
    "        let args = '';\n"
    "        try { args = JSON.stringify(JSON.parse(rawArgs), null, 2); } catch(e) { args = String(rawArgs); }\n"
    "        return '<div class=\"tool-call\"><div class=\"tc-name\">🔧 ' + esc(fn.name || '') + '</div><pre style=\"margin:4px 0 0;font-size:12px\">' + esc(args) + '</pre></div>';\n"
    "      }).join('');\n"
    "    }\n"
    "    html += '</div>';\n"
    "    html += '</div>';\n"
    "    return html;\n"
    "  }).join('');\n"
    "}\n"
    "function renderMessageContent(m) {\n"
    "  if (!m) return '';\n"
    "  if (typeof m.content === 'string') return '<div class=\"msg-part msg-text\">' + esc(m.content) + '</div>';\n"
    "  if (Array.isArray(m.content)) return m.content.map((p, i) => renderContentPart(p, i)).join('');\n"
    "  if (m.content == null) return '';\n"
    "  return '<div class=\"msg-part msg-text\">' + esc(JSON.stringify(m.content, null, 2)) + '</div>';\n"
    "}\n"
    "function renderContentPart(p, index) {\n"
    "  const url = imageUrlFromPart(p);\n"
    "  if (url) {\n"
    "    const label = imageLabelFromUrl(url);\n"
    "    return '<div class=\"msg-part\"><img src=\"' + escAttr(url) + '\" class=\"msg-image\" alt=\"Message image ' + (index + 1) + '\" loading=\"lazy\"><div class=\"msg-image-meta\">' + esc(label) + '</div></div>';\n"
    "  }\n"
    "  if (p && p.type === 'text') return '<div class=\"msg-part msg-text\">' + esc(p.text || '') + '</div>';\n"
    "  return '<div class=\"msg-part msg-text\">' + esc(contentPartText(p)) + '</div>';\n"
    "}\n"
    "function renderMessageHead(headClass, role, index, marker, collapseUid) {\n"
    "  let html = '<div class=\"' + headClass + '\">';\n"
    "  if (index !== null && index !== undefined) html += '<span class=\"msg-index\">#' + index + '</span>';\n"
    "  html += '<span class=\"msg-role\">' + esc(role || 'unknown') + '</span>';\n"
    "  if (marker) html += '<span class=\"diff-mark\">' + esc(marker) + '</span>';\n"
    "  if (collapseUid) html += '<span class=\"msg-head-action\"><button class=\"msg-collapse\" title=\"Toggle collapse\" onclick=\"toggleMsgCollapse(\\'' + collapseUid + '\\', this)\">↓</button></span>';\n"
    "  html += '</div>';\n"
    "  return html;\n"
    "}\n"
    "function messageText(m) {\n"
    "  let contentText = '';\n"
    "  if (typeof m.content === 'string') {\n"
    "    contentText = m.content;\n"
    "  } else if (Array.isArray(m.content)) {\n"
    "    contentText = m.content.map(contentPartText).filter(t => t !== '').join('\\n');\n"
    "  } else if (m.content != null) {\n"
    "    contentText = JSON.stringify(m.content, null, 2);\n"
    "  }\n"
    "  return contentText;\n"
    "}\n"
    "function contentPartText(p) {\n"
    "  if (!p) return '';\n"
    "  if (p.type === 'text') return p.text || '';\n"
    "  const url = imageUrlFromPart(p);\n"
    "  if (url) return '[Image: ' + imageLabelFromUrl(url) + ']';\n"
    "  if (p.type === 'input_audio') {\n"
    "    const format = p.input_audio && p.input_audio.format ? ': ' + p.input_audio.format : '';\n"
    "    return '[input_audio' + format + ']';\n"
    "  }\n"
    "  return '[' + (p.type || 'unknown') + ']';\n"
    "}\n"
    "function imageUrlFromPart(p) {\n"
    "  if (!p || typeof p !== 'object') return '';\n"
    "  let url = '';\n"
    "  if (typeof p.image_url === 'string') url = p.image_url;\n"
    "  else if (p.image_url && typeof p.image_url.url === 'string') url = p.image_url.url;\n"
    "  if (!url && typeof p.url === 'string') url = p.url;\n"
    "  if (!url && typeof p.data === 'string') {\n"
    "    const mime = imageMimeFromPart(p);\n"
    "    if (mime) url = 'data:' + mime + ';base64,' + p.data;\n"
    "  }\n"
    "  return isRenderableImageDataUrl(url) ? url : '';\n"
    "}\n"
    "function imageMimeFromPart(p) {\n"
    "  const rawMime = String(p.mime_type || p.mimeType || '');\n"
    "  if (rawMime.toLowerCase().indexOf('image/') === 0) return rawMime;\n"
    "  const format = String(p.format || '').toLowerCase();\n"
    "  if (format === 'jpg') return 'image/jpeg';\n"
    "  if (format === 'jpeg' || format === 'png' || format === 'gif' || format === 'webp') return 'image/' + format;\n"
    "  return '';\n"
    "}\n"
    "function isRenderableImageDataUrl(url) {\n"
    "  const lower = String(url || '').toLowerCase();\n"
    "  return lower.indexOf('data:image/') === 0 && lower.indexOf(';base64,') > 0;\n"
    "}\n"
    "function imageLabelFromUrl(url) {\n"
    "  const s = String(url || '');\n"
    "  const end = s.toLowerCase().indexOf(';base64,');\n"
    "  return end > 5 ? s.substring(5, end) + ' base64 image' : 'base64 image';\n"
    "}\n"
    "function messageNeedsCollapse(text) {\n"
    "  const value = String(text == null ? '' : text);\n"
    "  return value.split('\\n').length > 8 || value.length > 3000;\n"
    "}\n"
    "function toggleMsgCollapse(uid, btn) {\n"
    "  const el = document.getElementById(uid);\n"
    "  if (!el) return;\n"
    "  if (el.classList.contains('collapsed')) {\n"
    "    el.classList.remove('collapsed');\n"
    "    btn.textContent = '↑';\n"
    "  } else {\n"
    "    el.classList.add('collapsed');\n"
    "    btn.textContent = '↓';\n"
    "  }\n"
    "}\n"
    "function renderMessagesView(g, req) {\n"
    "  return renderMessages(req.messages || [], true, 'request-msg') + renderResponseBlock(g);\n"
    "}\n"
    "function renderResponseBlock(g) {\n"
    "  let head = '<div class=\"response-section\"><div class=\"response-section-head\"><span>Response</span>';\n"
    "  if (!g.response) {\n"
    "    head += '<span class=\"badge none\">No Response</span></div>';\n"
    "    head += '<div style=\"color:#6b7280;font-size:13px\">No response was recorded for this request.</div></div>';\n"
    "    return head;\n"
    "  }\n"
    "  const status = g.response.status;\n"
    "  const ok = status >= 200 && status < 300;\n"
    "  const badgeClass = 'badge ' + (ok ? 'ok' : (status === 0 ? 'none' : 'err'));\n"
    "  const badgeText = status === 0 ? 'No Status' : (ok ? status : 'Error ' + status);\n"
    "  head += '<span class=\"' + badgeClass + '\">' + esc(badgeText) + '</span>';\n"
    "  if (g.response.ts) head += '<span style=\"font-size:12px;color:#6b7280;font-weight:400\">' + esc(g.response.ts) + '</span>';\n"
    "  head += '</div>';\n"
    "  const msg = extractResponseMessage(g.response.body);\n"
    "  let bodyHtml;\n"
    "  if (msg) {\n"
    "    bodyHtml = renderMessages([msg], false);\n"
    "  } else {\n"
    "    // Body is not OpenAI-shaped (transport error, empty stream, plain text\n"
    "    // error from the upstream). Show it raw so failures stay diagnosable.\n"
    "    const text = String(g.response.body == null ? '' : g.response.body);\n"
    "    bodyHtml = '<pre class=\"raw\">' + esc(text) + '</pre>';\n"
    "  }\n"
    "  return head + bodyHtml + '</div>';\n"
    "}\n"
    "function extractResponseMessage(body) {\n"
    "  // OpenAI-compatible responses come in three shapes in the log:\n"
    "  //   1. Non-streaming JSON with choices[0].message.\n"
    "  //   2. SSE stream of `data: {delta: ...}` lines (terminated by [DONE]).\n"
    "  //   3. Plain error text written by the agent itself (transport error,\n"
    "  //      `(empty stream response)`, etc.) — caller falls back to raw.\n"
    "  // Returns a synthetic assistant message {role, content, tool_calls} or null.\n"
    "  if (!body) return null;\n"
    "  const text = String(body);\n"
    "  // Try non-streaming JSON first.\n"
    "  try {\n"
    "    const obj = JSON.parse(text);\n"
    "    if (obj && Array.isArray(obj.choices) && obj.choices.length > 0) {\n"
    "      const m = obj.choices[0].message || {};\n"
    "      return {role: m.role || 'assistant', content: m.content || '', tool_calls: m.tool_calls || []};\n"
    "    }\n"
    "    if (obj && obj.error) {\n"
    "      const errStr = typeof obj.error === 'string' ? obj.error : JSON.stringify(obj.error, null, 2);\n"
    "      return {role: 'assistant', content: 'Error: ' + errStr};\n"
    "    }\n"
    "  } catch(e) {}\n"
    "  // Try SSE stream — accumulate content and tool_calls across `data:` events.\n"
    "  const lines = text.split('\\n');\n"
    "  let hasData = false;\n"
    "  let content = '';\n"
    "  const toolCalls = {};\n"
    "  for (const rawLine of lines) {\n"
    "    const line = rawLine.trim();\n"
    "    if (!line.startsWith('data:')) continue;\n"
    "    const data = line.substring(5).trim();\n"
    "    if (!data || data === '[DONE]') continue;\n"
    "    let event;\n"
    "    try { event = JSON.parse(data); } catch(e) { continue; }\n"
    "    hasData = true;\n"
    "    const choice = (event.choices && event.choices[0]) || null;\n"
    "    if (!choice) continue;\n"
    "    const delta = choice.delta || choice.message || {};\n"
    "    if (typeof delta.content === 'string') content += delta.content;\n"
    "    else if (Array.isArray(delta.content)) {\n"
    "      for (const p of delta.content) {\n"
    "        if (p && p.type === 'text' && typeof p.text === 'string') content += p.text;\n"
    "      }\n"
    "    }\n"
    "    if (Array.isArray(delta.tool_calls)) {\n"
    "      for (const tc of delta.tool_calls) {\n"
    "        const k = tc.index != null ? tc.index : (tc.id || Object.keys(toolCalls).length);\n"
    "        if (!toolCalls[k]) toolCalls[k] = {type: 'function', function: {name: '', arguments: ''}};\n"
    "        if (tc.id) toolCalls[k].id = tc.id;\n"
    "        if (tc.function) {\n"
    "          if (tc.function.name) toolCalls[k].function.name += tc.function.name;\n"
    "          if (tc.function.arguments) toolCalls[k].function.arguments += tc.function.arguments;\n"
    "        }\n"
    "      }\n"
    "    }\n"
    "  }\n"
    "  if (!hasData) return null;\n"
    "  const tcArr = Object.keys(toolCalls).sort((a, b) => (+a) - (+b)).map(k => toolCalls[k]);\n"
    "  return {role: 'assistant', content: content, tool_calls: tcArr};\n"
    "}\n"
    "function renderDiff(oldMsgs, newMsgs) {\n"
    "  // LCS over whole messages (compared by canonical serialization) so an\n"
    "  // appended turn shows only the new tail as added, not everything after\n"
    "  // the first insertion. Matches git's line-diff model at message scope.\n"
    "  const a = oldMsgs.map(serializeMsg);\n"
    "  const b = newMsgs.map(serializeMsg);\n"
    "  const n = a.length, mm = b.length;\n"
    "  const lcs = [];\n"
    "  for (let i = 0; i <= n; i++) { lcs.push(new Array(mm + 1).fill(0)); }\n"
    "  for (let i = n - 1; i >= 0; i--) {\n"
    "    for (let j = mm - 1; j >= 0; j--) {\n"
    "      lcs[i][j] = a[i] === b[j] ? lcs[i + 1][j + 1] + 1 : Math.max(lcs[i + 1][j], lcs[i][j + 1]);\n"
    "    }\n"
    "  }\n"
    "  let i = 0, j = 0, blockIndex = 0, html = '';\n"
    "  while (i < n && j < mm) {\n"
    "    if (a[i] === b[j]) { html += diffMsgBlock(newMsgs[j], 'same', blockIndex++, j); i++; j++; }\n"
    "    else if (lcs[i + 1][j] >= lcs[i][j + 1]) { html += diffMsgBlock(oldMsgs[i], 'removed', blockIndex++, i); i++; }\n"
    "    else { html += diffMsgBlock(newMsgs[j], 'added', blockIndex++, j); j++; }\n"
    "  }\n"
    "  while (i < n) { html += diffMsgBlock(oldMsgs[i], 'removed', blockIndex++, i); i++; }\n"
    "  while (j < mm) { html += diffMsgBlock(newMsgs[j], 'added', blockIndex++, j); j++; }\n"
    "  return html || '<div style=\"color:#6b7280;font-size:13px\">No differences.</div>';\n"
    "}\n"
    "function serializeMsg(m) {\n"
    "  let s = (m.role || '') + '\\u0001';\n"
    "  if (typeof m.content === 'string') s += m.content;\n"
    "  else if (Array.isArray(m.content)) s += m.content.map(serializeContentPart).join('\\n');\n"
    "  if (m.tool_calls) s += '\\u0002' + JSON.stringify(m.tool_calls);\n"
    "  if (m.tool_call_id) s += '\\u0003' + m.tool_call_id;\n"
    "  return s;\n"
    "}\n"
    "function serializeContentPart(p) {\n"
    "  if (!p) return '';\n"
    "  if (p.type === 'text') return 'text:' + (p.text || '');\n"
    "  const url = imageUrlFromPart(p);\n"
    "  if (url) return (p.type || 'image') + ':' + url;\n"
    "  try { return JSON.stringify(p); } catch(e) { return String(p); }\n"
    "}\n"
    "function diffMsgBlock(m, kind, index, messageIndex) {\n"
    "  const mark = kind === 'added' ? '+' : (kind === 'removed' ? '-' : '=');\n"
    "  const cls = kind === 'added' ? 'diff-add' : (kind === 'removed' ? 'diff-del' : 'diff-same');\n"
    "  let text = messageText(m);\n"
    "  if (m.tool_calls && m.tool_calls.length) {\n"
    "    text += (text ? '\\n' : '') + m.tool_calls.map(tc => '🔧 ' + (tc.function ? tc.function.name : '') + ' ' + (tc.function ? tc.function.arguments : '')).join('\\n');\n"
    "  }\n"
    "  const uid = 'diff-msg-' + index;\n"
    "  const needsCollapse = messageNeedsCollapse(text);\n"
    "  let html = '<div class=\"diff-msg ' + kind + '\">';\n"
    "  html += renderMessageHead('diff-msg-head' + ' role-' + cssToken(m.role || 'unknown'), m.role, messageIndex, mark, needsCollapse ? uid : null);\n"
    "  html += '<div class=\"msg-content diff-line ' + cls + (needsCollapse ? ' collapsed' : '') + '\" id=\"' + uid + '\">' + renderMessageContent(m) + '</div>';\n"
    "  html += '</div>';\n"
    "  return html;\n"
    "}\n"
    "function parseBody(body) {\n"
    "  try { return JSON.parse(body); } catch(e) { return {}; }\n"
    "}\n"
    "function esc(s) {\n"
    "  return String(s == null ? '' : s)\n"
    "    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')\n"
    "    .replace(/\"/g, '&quot;').replace(/'/g, '&#39;');\n"
    "}\n"
    "function escAttr(s) {\n"
    "  return esc(s);\n"
    "}\n"
    "function cssToken(s) {\n"
    "  return String(s == null ? '' : s).replace(/[^a-zA-Z0-9_-]/g, '_') || 'unknown';\n"
    "}\n"
    "function computeDiffStats(oldMsgs, newMsgs) {\n"
    "  const a = oldMsgs.map(serializeMsg);\n"
    "  const b = newMsgs.map(serializeMsg);\n"
    "  const n = a.length, mm = b.length;\n"
    "  const lcs = [];\n"
    "  for (let i = 0; i <= n; i++) { lcs.push(new Array(mm + 1).fill(0)); }\n"
    "  for (let i = n - 1; i >= 0; i--) {\n"
    "    for (let j = mm - 1; j >= 0; j--) {\n"
    "      lcs[i][j] = a[i] === b[j] ? lcs[i + 1][j + 1] + 1 : Math.max(lcs[i + 1][j], lcs[i][j + 1]);\n"
    "    }\n"
    "  }\n"
    "  let i = 0, j = 0, added = 0, removed = 0, modified = 0;\n"
    "  while (i < n && j < mm) {\n"
    "    if (a[i] === b[j]) { i++; j++; }\n"
    "    else if (lcs[i + 1][j] >= lcs[i][j + 1]) { removed++; i++; }\n"
    "    else { added++; j++; }\n"
    "  }\n"
    "  while (i < n) { removed++; i++; }\n"
    "  while (j < mm) { added++; j++; }\n"
    "  return {added, removed, modified};\n"
    "}\n"
    "loadFileList();\n"
    "  </script>\n"
    "</body>\n"
    "</html>\n";
