#pragma once

// Standalone viewer for the agent's raw LLM HTTP logs. Served at GET /llm-logs.
// It reads JSONL files via /api/llm-logs and /api/llm-logs/file/<name>, pairs
// each request with the response that immediately follows it, renders the
// request `messages` array in full, and offers an inline git-style diff of a
// request's messages against the previous request.
static const char* CONFIG_WEB_LLM_HTML =
    "<!DOCTYPE html>\n"
    "<html lang=\"zh-CN\">\n"
    "<head>\n"
    "  <meta charset=\"UTF-8\">\n"
    "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
    "  <title>Aiden LLM Logs</title>\n"
    "  <style>\n"
    "    *{box-sizing:border-box}body{margin:0;background:#f9fafb;color:#111827;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif}\n"
    "    .topbar{display:flex;align-items:center;gap:12px;padding:14px 20px;background:#fff;border-bottom:1px solid #e5e7eb}\n"
    "    .topbar h1{margin:0;font-size:18px}.topbar a{color:#2563eb;text-decoration:none;font-size:14px}.topbar a:hover{text-decoration:underline}\n"
    "    .layout{display:flex;height:calc(100vh - 53px)}\n"
    "    .sidebar{flex:0 0 280px;border-right:1px solid #e5e7eb;background:#fff;overflow-y:auto}\n"
    "    .sidebar-head{display:flex;align-items:center;justify-content:space-between;padding:12px 14px;border-bottom:1px solid #f0f1f4}\n"
    "    .sidebar-head .button{padding:5px 10px;font-size:12px}\n"
    "    .file-row{display:block;width:100%;border:0;border-bottom:1px solid #f0f1f4;background:transparent;text-align:left;padding:10px 14px;cursor:pointer;font:inherit;color:#111827}\n"
    "    .file-row:hover{background:#f9fafb}.file-row.active{background:#eff6ff}\n"
    "    .file-name{font-size:13px;font-weight:600;word-break:break-all}.file-meta{font-size:11px;color:#6b7280;margin-top:2px}\n"
    "    .detail{flex:1;display:flex;overflow:hidden}\n"
    "    .request-list{flex:0 0 360px;border-right:1px solid #e5e7eb;background:#fff;display:flex;flex-direction:column;overflow:hidden}\n"
    "    .request-detail{flex:1;display:flex;flex-direction:column;overflow:hidden;background:#f9fafb}\n"
    "    .request-list-head,.request-detail-head{padding:12px 14px;border-bottom:1px solid #e5e7eb;font-size:13px;font-weight:600;color:#111827;background:#f9fafb}\n"
    "    #requestList,#requestDetail{flex:1;overflow-y:auto}\n"
    "    .request-item{display:block;width:100%;border:0;border-bottom:1px solid #f0f1f4;background:transparent;text-align:left;padding:12px 14px;cursor:pointer;font:inherit;color:#111827}\n"
    "    .request-item:hover{background:#f9fafb}.request-item.active{background:#eff6ff;border-left:3px solid #2563eb}\n"
    "    .request-item-head{display:flex;align-items:center;gap:8px;margin-bottom:6px}\n"
    "    .request-item-index{font-size:12px;font-weight:700;color:#6b7280}\n"
    "    .request-item-preview{font-size:13px;color:#111827;overflow:hidden;text-overflow:ellipsis;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;line-height:1.4}\n"
    "    .empty{color:#6b7280;font-size:14px;padding:24px 0}\n"
    "    .group{border:1px solid #e5e7eb;border-radius:12px;background:#fff;margin-bottom:16px;overflow:hidden}\n"
    "    .group-head{display:flex;align-items:center;gap:10px;padding:10px 14px;background:#f3f4f6;border-bottom:1px solid #e5e7eb;flex-wrap:wrap}\n"
    "    .group-title{font-size:14px;font-weight:700}\n"
    "    .badge{font-size:12px;padding:2px 8px;border-radius:999px;font-weight:600}\n"
    "    .badge.ok{background:#dcfce7;color:#166534}.badge.err{background:#fee2e2;color:#991b1b}.badge.none{background:#fef3c7;color:#92400e}\n"
    "    .group-actions{margin-left:auto;display:flex;gap:8px}\n"
    "    .button{border:0;border-radius:8px;padding:6px 12px;font-size:13px;font-weight:600;cursor:pointer;background:#f3f4f6;color:#111827}\n"
    "    .button.primary{background:#2563eb;color:#fff}.button.active{background:#2563eb;color:#fff}.button:hover{opacity:.9}\n"
    "    .group-body{padding:12px 14px}\n"
    "    .msg{border:1px solid #e5e7eb;border-radius:8px;margin-bottom:10px;overflow:hidden}\n"
    "    .msg-head{padding:6px 10px;background:#f9fafb;border-bottom:1px solid #f0f1f4;font-size:12px;font-weight:700;text-transform:uppercase;letter-spacing:.03em;color:#374151}\n"
    "    .role-system{color:#7c3aed}.role-user{color:#2563eb}.role-assistant{color:#059669}.role-tool{color:#b45309}\n"
    "    .msg-content{padding:8px 10px;white-space:pre-wrap;word-break:break-word;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:12.5px;line-height:1.5}\n"
    "    .tool-call{margin-top:8px;border-top:1px dashed #e5e7eb;padding-top:8px}\n"
    "    .tool-call .tc-name{font-weight:700;color:#b45309;font-size:12.5px}\n"
    "    .diff-line{white-space:pre-wrap;word-break:break-word;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:12.5px;line-height:1.5;padding:2px 8px;border-left:3px solid transparent}\n"
    "    .diff-add{background:#ecfdf5;border-left-color:#059669}\n"
    "    .diff-del{background:#fef2f2;border-left-color:#dc2626;color:#7f1d1d}\n"
    "    .diff-same{color:#6b7280}\n"
    "    .diff-msg{margin-bottom:10px;border:1px solid #e5e7eb;border-radius:8px;overflow:hidden}\n"
    "    .diff-msg-head{padding:6px 10px;background:#f9fafb;border-bottom:1px solid #f0f1f4;font-size:12px;font-weight:700}\n"
    "    .diff-msg.added .diff-msg-head{background:#ecfdf5;color:#166534}\n"
    "    .diff-msg.removed .diff-msg-head{background:#fef2f2;color:#991b1b}\n"
    "    .raw-toggle{font-size:12px;color:#6b7280;cursor:pointer;text-decoration:underline;margin-top:8px;display:inline-block}\n"
    "    pre.raw{white-space:pre-wrap;word-break:break-word;background:#0b1021;color:#d6e2ff;padding:10px;border-radius:8px;font-size:12px;overflow-x:auto}\n"
    "  </style>\n"
    "</head>\n"
    "<body>\n"
    "  <div class=\"topbar\">\n"
    "    <a href=\"/\">\xe2\x86\x90 \xe8\xbf\x94\xe5\x9b\x9e\xe9\x85\x8d\xe7\xbd\xae</a>\n"
    "    <h1>LLM HTTP \xe6\x97\xa5\xe5\xbf\x97</h1>\n"
    "  </div>\n"
    "  <div class=\"layout\">\n"
    "    <div class=\"sidebar\">\n"
    "      <div class=\"sidebar-head\">\n"
    "        <span style=\"font-size:13px;font-weight:600\">\xe6\x97\xa5\xe5\xbf\x97\xe6\x96\x87\xe4\xbb\xb6</span>\n"
    "        <button class=\"button\" onclick=\"loadFileList()\">\xe5\x88\xb7\xe6\x96\xb0</button>\n"
    "      </div>\n"
    "      <div id=\"fileList\"></div>\n"
    "    </div>\n"
    "    <div class=\"detail\">\n"
    "      <div class=\"request-list\" id=\"requestList\">\n"
    "        <div class=\"empty\">\xe9\x80\x89\xe6\x8b\xa9\xe5\xb7\xa6\xe4\xbe\xa7\xe6\x97\xa5\xe5\xbf\x97\xe6\x96\x87\xe4\xbb\xb6\xe6\x9f\xa5\xe7\x9c\x8b\xe8\xaf\xb7\xe6\xb1\x82\xe3\x80\x82</div>\n"
    "      </div>\n"
    "      <div class=\"request-detail\" id=\"requestDetail\">\n"
    "        <div class=\"empty\">\xe9\x80\x89\xe6\x8b\xa9\xe5\xb7\xa6\xe4\xbe\xa7\xe8\xaf\xb7\xe6\xb1\x82\xe6\x9f\xa5\xe7\x9c\x8b\xe8\xaf\xa6\xe6\x83\x85\xe3\x80\x82</div>\n"
    "      </div>\n"
    "    </div>\n"
    "  </div>\n"
    "  <script>\n"
    "let state = {files: [], selectedFile: null, groups: [], selectedRequest: null};\n"
    "async function request(url) {\n"
    "  const res = await fetch(url);\n"
    "  const text = await res.text();\n"
    "  let body = {};\n"
    "  try { body = text ? JSON.parse(text) : {}; } catch(err) { body = {ok: false, error: text || err.message}; }\n"
    "  if (!res.ok) throw new Error(body.error || ('HTTP ' + res.status));\n"
    "  return body;\n"
    "}\n"
    "async function loadFileList() {\n"
    "  try {\n"
    "    const data = await request('/api/llm-logs');\n"
    "    state.files = data.files || [];\n"
    "    renderFileList();\n"
    "  } catch(err) {\n"
    "    document.getElementById('fileList').innerHTML = '<div class=\"empty\" style=\"padding:12px\">加载失败: ' + esc(err.message) + '</div>';\n"
    "  }\n"
    "}\n"
    "function renderFileList() {\n"
    "  const el = document.getElementById('fileList');\n"
    "  if (state.files.length === 0) {\n"
    "    el.innerHTML = '<div class=\"empty\" style=\"padding:12px\">暂无日志文件。</div>';\n"
    "    return;\n"
    "  }\n"
    "  el.innerHTML = state.files.map((f, i) => {\n"
    "    const active = state.selectedFile && state.selectedFile.name === f.name ? ' active' : '';\n"
    "    const kb = Math.round((f.size_bytes || 0) / 1024);\n"
    "    return '<button class=\"file-row' + active + '\" onclick=\"loadFile(' + i + ')\">' +\n"
    "           '<div class=\"file-name\">' + esc(f.name) + '</div>' +\n"
    "           '<div class=\"file-meta\">' + kb + ' KB</div>' +\n"
    "           '</button>';\n"
    "  }).join('');\n"
    "}\n"
    "async function loadFile(index) {\n"
    "  const f = state.files[index];\n"
    "  if (!f) return;\n"
    "  state.selectedFile = f;\n"
    "  renderFileList();\n"
    "  document.getElementById('detail').innerHTML = '<div class=\"empty\">加载中...</div>';\n"
    "  try {\n"
    "    const data = await request('/api/llm-logs/file/' + encodeURIComponent(f.name));\n"
    "    const lines = (data.content || '').trim().split('\\n').filter(l => l);\n"
    "    const entries = [];\n"
    "    for (let i = 0; i < lines.length; i++) {\n"
    "      try { entries.push(JSON.parse(lines[i])); } catch(e) {}\n"
    "    }\n"
    "    state.groups = groupEntries(entries);\n"
    "    renderGroups();\n"
    "  } catch(err) {\n"
    "    document.getElementById('detail').innerHTML = '<div class=\"empty\">加载失败: ' + esc(err.message) + '</div>';\n"
    "  }\n"
    "}\n"
    "function groupEntries(entries) {\n"
    "  const groups = [];\n"
    "  for (let i = 0; i < entries.length; i++) {\n"
    "    const e = entries[i];\n"
    "    if (e.kind !== 'request') continue;\n"
    "    const g = {request: e, response: null};\n"
    "    if (i + 1 < entries.length && entries[i + 1].kind === 'response') {\n"
    "      g.response = entries[i + 1];\n"
    "      i++;\n"
    "    }\n"
    "    groups.push(g);\n"
    "  }\n"
    "  return groups;\n"
    "}\n"
    "function renderGroups() {\n"
    "  const listEl = document.getElementById('requestList');\n"
    "  const detailEl = document.getElementById('requestDetail');\n"
    "  if (state.groups.length === 0) {\n"
    "    listEl.innerHTML = '<div class=\"empty\" style=\"padding:12px\">此文件无有效请求。</div>';\n"
    "    detailEl.innerHTML = '<div class=\"empty\">选择左侧请求查看详情。</div>';\n"
    "    return;\n"
    "  }\n"
    "  listEl.innerHTML = state.groups.map((g, i) => renderRequestItem(g, i)).join('');\n"
    "  if (state.selectedRequest === null) {\n"
    "    state.selectedRequest = 0;\n"
    "  }\n"
    "  renderRequestDetail();\n"
    "}\n"
    "function renderRequestItem(g, idx) {\n"
    "  const req = parseBody(g.request.body);\n"
    "  const messages = req.messages || [];\n"
    "  const lastMsg = messages.length > 0 ? messages[messages.length - 1] : null;\n"
    "  const preview = lastMsg ? (lastMsg.content || JSON.stringify(lastMsg).substring(0, 100)) : '无消息内容';\n"
    "  const status = !g.response ? 'none' : (g.response.status >= 200 && g.response.status < 300 ? 'ok' : 'err');\n"
    "  const badgeText = !g.response ? '无响应' : (status === 'ok' ? g.response.status : '错误 ' + g.response.status);\n"
    "  const badgeClass = 'badge ' + status;\n"
    "  const active = state.selectedRequest === idx ? ' active' : '';\n"
    "  let html = '<button class=\"request-item' + active + '\" onclick=\"selectRequest(' + idx + ')\">';\n"
    "  html += '<div class=\"request-item-head\">';\n"
    "  html += '<span class=\"request-item-index\">#' + (idx + 1) + '</span>';\n"
    "  html += '<span class=\"' + badgeClass + '\">' + esc(badgeText) + '</span>';\n"
    "  html += '<span style=\"font-size:11px;color:#9ca3af;margin-left:auto\">' + esc(g.request.ts.substring(11, 19)) + '</span>';\n"
    "  html += '</div>';\n"
    "  html += '<div class=\"request-item-preview\">' + esc(preview) + '</div>';\n"
    "  html += '</button>';\n"
    "  return html;\n"
    "}\n"
    "function selectRequest(idx) {\n"
    "  state.selectedRequest = idx;\n"
    "  renderGroups();\n"
    "}\n"
    "function renderRequestDetail() {\n"
    "  const detailEl = document.getElementById('requestDetail');\n"
    "  if (state.selectedRequest === null || !state.groups[state.selectedRequest]) {\n"
    "    detailEl.innerHTML = '<div class=\"empty\">选择左侧请求查看详情。</div>';\n"
    "    return;\n"
    "  }\n"
    "  const idx = state.selectedRequest;\n"
    "  const g = state.groups[idx];\n"
    "  const req = parseBody(g.request.body);\n"
    "  const resp = g.response ? parseBody(g.response.body) : null;\n"
    "  const status = !g.response ? 'none' : (g.response.status >= 200 && g.response.status < 300 ? 'ok' : 'err');\n"
    "  const badgeText = !g.response ? '无响应' : (status === 'ok' ? g.response.status : '错误 ' + g.response.status);\n"
    "  const badgeClass = 'badge ' + status;\n"
    "  let html = '<div class=\"group\">';\n"
    "  html += '<div class=\"group-head\">';\n"
    "  html += '<span class=\"group-title\">请求 #' + (idx + 1) + '</span>';\n"
    "  html += '<span class=\"' + badgeClass + '\">' + esc(badgeText) + '</span>';\n"
    "  html += '<span style=\"font-size:12px;color:#6b7280\">' + esc(g.request.ts) + '</span>';\n"
    "  html += '<div class=\"group-actions\">';\n"
    "  html += '<button class=\"button active\" id=\"msg-btn\" onclick=\"showDetailView(\\\\'messages\\\\')\">\xe6\xb6\x88\xe6\x81\xaf</button>';\n"
    "  if (idx > 0) {\n"
    "    html += '<button class=\"button\" id=\"diff-btn\" onclick=\"showDetailView(\\\\'diff\\\\')\">\xe5\xaf\xb9\xe6\xaf\x94</button>';\n"
    "  }\n"
    "  html += '<button class=\"button\" id=\"raw-btn\" onclick=\"showDetailView(\\\\'raw\\\\')\">\xe5\x8e\x9f\xe5\xa7\x8b</button>';\n"
    "  html += '</div></div>';\n"
    "  html += '<div class=\"group-body\" id=\"detail-body\">' + renderMessages(req.messages || []) + '</div>';\n"
    "  html += '</div>';\n"
    "  detailEl.innerHTML = html;\n"
    "}\n"
    "function showDetailView(view) {\n"
    "  const idx = state.selectedRequest;\n"
    "  if (idx === null) return;\n"
    "  const g = state.groups[idx];\n"
    "  if (!g) return;\n"
    "  document.getElementById('msg-btn').className = view === 'messages' ? 'button active' : 'button';\n"
    "  const diffBtn = document.getElementById('diff-btn');\n"
    "  if (diffBtn) diffBtn.className = view === 'diff' ? 'button active' : 'button';\n"
    "  document.getElementById('raw-btn').className = view === 'raw' ? 'button active' : 'button';\n"
    "  const body = document.getElementById('detail-body');\n"
    "  const req = parseBody(g.request.body);\n"
    "  if (view === 'messages') {\n"
    "    body.innerHTML = renderMessages(req.messages || []);\n"
    "  } else if (view === 'diff' && idx > 0) {\n"
    "    const prevReq = parseBody(state.groups[idx - 1].request.body);\n"
    "    body.innerHTML = renderDiff(prevReq.messages || [], req.messages || []);\n"
    "  } else if (view === 'raw') {\n"
    "    body.innerHTML = '<pre class=\"raw\">' + esc(JSON.stringify(req, null, 2)) + '</pre>';\n"
    "  }\n"
    "}\n"
    "      html += esc(m.content);\n"
    "    } else if (Array.isArray(m.content)) {\n"
    "      html += m.content.map(p => {\n"
    "        if (p.type === 'text') return esc(p.text || '');\n"
    "        if (p.type === 'image_url') return esc('[图片: ' + (p.image_url ? String(p.image_url.url || '').substring(0, 60) : '') + '...]');\n"
    "        return '[' + (p.type || 'unknown') + ']';\n"
    "      }).join('\\n');\n"
    "    }\n"
    "    if (m.tool_calls && m.tool_calls.length > 0) {\n"
    "      html += m.tool_calls.map(tc => {\n"
    "        const fn = (tc && tc.function) || {};\n"
    "        const rawArgs = fn.arguments == null ? '' : fn.arguments;\n"
    "        let args = '';\n"
    "        try { args = JSON.stringify(JSON.parse(rawArgs), null, 2); } catch(e) { args = String(rawArgs); }\n"
    "        return '<div class=\"tool-call\"><div class=\"tc-name\">🔧 ' + esc(fn.name || '') + '</div><pre style=\"margin:4px 0 0;font-size:12px\">' + esc(args) + '</pre></div>';\n"
    "      }).join('');\n"
    "    }\n"
    "    html += '</div></div>';\n"
    "    return html;\n"
    "  }).join('');\n"
    "}\n"
    "function renderDiff(oldMsgs, newMsgs) {\n"
    "  // LCS over whole messages (compared by canonical serialization) so an\n"
    "  // appended turn shows only the new tail as added, not everything after\n"
    "  // the first insertion. Matches git's line-diff model at message scope.\n"
    "  const a = oldMsgs.map(serializeMsg);\n"
    "  const b = newMsgs.map(serializeMsg);\n"
    "  const n = a.length, mm = b.length;\n"
    "  const lcs = [];\n"
    "  for (let i = 0; i <= n; i++) { lcs.push(new Array(mm + 1).fill(0)); }\n"
    "  for (let i = n - 1; i >= 0; i--) {\n"
    "    for (let j = mm - 1; j >= 0; j--) {\n"
    "      lcs[i][j] = a[i] === b[j] ? lcs[i + 1][j + 1] + 1 : Math.max(lcs[i + 1][j], lcs[i][j + 1]);\n"
    "    }\n"
    "  }\n"
    "  let i = 0, j = 0, html = '';\n"
    "  while (i < n && j < mm) {\n"
    "    if (a[i] === b[j]) { html += diffMsgBlock(newMsgs[j], 'same'); i++; j++; }\n"
    "    else if (lcs[i + 1][j] >= lcs[i][j + 1]) { html += diffMsgBlock(oldMsgs[i], 'removed'); i++; }\n"
    "    else { html += diffMsgBlock(newMsgs[j], 'added'); j++; }\n"
    "  }\n"
    "  while (i < n) { html += diffMsgBlock(oldMsgs[i], 'removed'); i++; }\n"
    "  while (j < mm) { html += diffMsgBlock(newMsgs[j], 'added'); j++; }\n"
    "  return html || '<div style=\"color:#6b7280;font-size:13px\">无差异。</div>';\n"
    "}\n"
    "function serializeMsg(m) {\n"
    "  let s = (m.role || '') + '\\u0001';\n"
    "  if (typeof m.content === 'string') s += m.content;\n"
    "  else if (Array.isArray(m.content)) s += m.content.map(p => p.type === 'text' ? p.text : '[' + (p.type || '?') + ']').join('\\n');\n"
    "  if (m.tool_calls) s += '\\u0002' + JSON.stringify(m.tool_calls);\n"
    "  if (m.tool_call_id) s += '\\u0003' + m.tool_call_id;\n"
    "  return s;\n"
    "}\n"
    "function diffMsgBlock(m, kind) {\n"
    "  const mark = kind === 'added' ? '\\u2795 ' : (kind === 'removed' ? '\\u2796 ' : '= ');\n"
    "  const cls = kind === 'added' ? 'diff-add' : (kind === 'removed' ? 'diff-del' : 'diff-same');\n"
    "  let text = '';\n"
    "  if (typeof m.content === 'string') text = m.content;\n"
    "  else if (Array.isArray(m.content)) text = m.content.map(p => p.type === 'text' ? p.text : '[' + (p.type || '?') + ']').join('\\n');\n"
    "  if (m.tool_calls && m.tool_calls.length) {\n"
    "    text += (text ? '\\n' : '') + m.tool_calls.map(tc => '🔧 ' + (tc.function ? tc.function.name : '') + ' ' + (tc.function ? tc.function.arguments : '')).join('\\n');\n"
    "  }\n"
    "  let html = '<div class=\"diff-msg ' + kind + '\">';\n"
    "  html += '<div class=\"diff-msg-head\">' + mark + esc(m.role || 'unknown') + '</div>';\n"
    "  html += '<div class=\"diff-line ' + cls + '\">' + esc(text) + '</div>';\n"
    "  html += '</div>';\n"
    "  return html;\n"
    "}\n"
    "function parseBody(body) {\n"
    "  try { return JSON.parse(body); } catch(e) { return {}; }\n"
    "}\n"
    "function esc(s) {\n"
    "  return String(s == null ? '' : s)\n"
    "    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')\n"
    "    .replace(/\"/g, '&quot;').replace(/'/g, '&#39;');\n"
    "}\n"
    "function cssToken(s) {\n"
    "  return String(s == null ? '' : s).replace(/[^a-zA-Z0-9_-]/g, '_') || 'unknown';\n"
    "}\n"
    "loadFileList();\n"
    "  </script>\n"
    "</body>\n"
    "</html>\n";
