#pragma once

static const char* CONFIG_WEB_HTML =
    "<!DOCTYPE html>\n"
    "<html lang=\"zh-CN\">\n"
    "<head>\n"
    "  <meta charset=\"UTF-8\">\n"
    "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
    "  <title>Aiden Setup</title>\n"
    "  <style>\n"
    "    *{box-sizing:border-box}body{margin:0;background:#fff;color:#111827;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif}"
    "    .page{max-width:1120px;margin:0 auto;padding:24px 16px 40px}"
    "    .hero{display:flex;align-items:center;gap:14px;margin-bottom:8px}.hero-logo{color:#111827;flex:0 0 auto;display:block}.hero-text h1{margin:0;font-size:24px;line-height:26px;color:#111827}"
    "    .card{background:#fff;border:1px solid #e5e7eb;border-radius:16px;padding:18px;margin-top:16px;box-shadow:0 1px 2px rgba(15,23,42,.04)}"
    "    .card-head{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:14px}.card-head h2,.card-head h3{margin:0;font-size:18px;color:#111827}"
    "    .subtle{color:#6b7280;font-size:13px}.fw-actions{display:flex;align-items:center;gap:10px;flex-wrap:wrap;margin-top:4px}.fw-actions .subtle{margin:0}.fw-actions .button{padding:7px 12px;font-size:13px}.fw-health{display:none;margin-top:4px;color:#6b7280;font-size:12px;line-height:1.4;word-break:break-word}.fw-health.error{color:#991b1b}.action-card{margin-top:12px}.ota-log-panel{display:none;margin-top:12px}.ota-log-head{display:flex;align-items:flex-end;justify-content:space-between;gap:12px;margin:12px 0 8px}.ota-log-title{font-size:15px;font-weight:700;color:#111827}.ota-log-head .button{padding:7px 12px;font-size:13px}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.field{display:flex;flex-direction:column;gap:6px}.field.hidden{display:none}.field-hint{font-size:12px;line-height:1.35;color:#6b7280}.wide{grid-column:1/-1}"
    "    label{font-size:13px;color:#374151}input,select,textarea{width:100%;padding:10px 12px;border:1px solid #d1d5db;border-radius:10px;background:#fff;color:#111827;font-size:14px;font-family:inherit;transition:border-color .15s,box-shadow .15s}input:focus,select:focus,textarea:focus{outline:none;border-color:#2563eb;box-shadow:0 0 0 3px rgba(37,99,235,.12)}textarea{min-height:92px;resize:vertical}input:disabled,select:disabled,textarea:disabled{background:#f9fafb;color:#6b7280;cursor:not-allowed}"
    "    .toolbar{display:flex;gap:10px;flex-wrap:wrap}.button{border:0;border-radius:10px;padding:9px 14px;font-size:14px;font-weight:600;cursor:pointer;transition:background .15s,border-color .15s}.button.primary{background:#2563eb;color:#fff}.button.primary:hover{background:#1d4ed8}.button.secondary{background:#f3f4f6;color:#111827}.button.secondary:hover{background:#e5e7eb}.button.ghost{background:transparent;border:1px solid #d1d5db;color:#374151}.button.ghost:hover{background:#f9fafb}.button:disabled{opacity:.5;cursor:not-allowed}"
    "    .wifi-list{display:flex;flex-direction:column;border:1px solid #e5e7eb;border-radius:12px;background:#fff;max-height:320px;overflow-y:auto}.wifi-row{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:12px 14px;border:0;border-bottom:1px solid #f0f1f4;background:transparent;color:#111827;text-align:left;font-family:inherit;font-size:inherit}.wifi-row:last-child{border-bottom:0}.wifi-row:hover{background:#f9fafb}.wifi-row.current{background:#ecfdf5}.wifi-row.saved{background:#eff6ff}.wifi-connect{flex:1 1 auto;min-width:0;border:0;background:transparent;padding:0;text-align:left;font:inherit;color:inherit;cursor:pointer}.wifi-main{font-size:15px;font-weight:600}.wifi-meta{font-size:12px;color:#6b7280;margin-top:3px}.wifi-state{display:flex;align-items:center;gap:10px;flex:0 0 auto;font-size:18px;font-weight:700;color:#059669}.wifi-state .button{padding:6px 10px;font-size:12px}.wifi-toggle-row{padding:10px 14px;border-top:1px solid #f0f1f4;background:#fff}.wifi-toggle-row .button{width:100%;padding:8px 10px;font-size:13px}"
    "    .banner{padding:12px 14px;border-radius:12px;background:#eff6ff;border:1px solid #bfdbfe;color:#1e3a8a;font-size:14px}.banner.error{background:#fef2f2;border-color:#fecaca;color:#991b1b}.details{margin-top:10px;display:none}.action-detail-text{display:none;margin:8px 0 0;padding:12px;border-radius:10px;background:#f9fafb;border:1px solid #e5e7eb;white-space:pre-wrap;word-break:break-word;font:12px/1.5 ui-monospace,SFMono-Regular,Menlo,monospace;color:#374151}"
    "    .agent-status-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.agent-status-item{border:1px solid #e5e7eb;border-radius:12px;padding:12px;background:#fff}.agent-status-label{display:block;font-size:12px;color:#6b7280;margin-bottom:5px}.agent-status-value{display:block;font-size:15px;font-weight:700;color:#374151}.agent-status-value.ok{color:#047857}.agent-status-value.warn{color:#b45309}.agent-status-value.error{color:#b91c1c}.agent-status-detail{margin-top:5px;font-size:12px;line-height:1.4;color:#6b7280;white-space:pre-wrap;word-break:break-word}"
    "    .agent-log-head{display:flex;align-items:flex-end;justify-content:space-between;gap:12px;margin:16px 0 8px}.agent-log-head h3{margin:0;font-size:15px;color:#111827}.agent-log-meta{margin-top:4px;font-size:12px;color:#6b7280;word-break:break-word}.agent-log-viewer{height:260px;overflow:auto;margin:0;padding:12px;border-radius:10px;background:#111827;color:#e5e7eb;border:1px solid #1f2937;white-space:pre-wrap;word-break:break-word;font:12px/1.5 ui-monospace,SFMono-Regular,Menlo,monospace}"
    "    .config-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.section-card{padding:16px;border-radius:12px;background:#fff;border:1px solid #e5e7eb}.section-card.mode-locked{background:#f9fafb}.section-card.mode-locked h3{color:#6b7280}.section-note{margin:-4px 0 12px}.section-actions{display:flex;gap:8px;flex-wrap:wrap}.section-actions .button{padding:7px 12px;font-size:13px}"
    "    .section-card .save-btn,.section-card .cancel-btn{display:none}.section-card.editing .edit-btn{display:none}.section-card.editing .save-btn,.section-card.editing .cancel-btn{display:inline-block}"
    "    .test-toast{position:fixed;top:0;left:0;right:0;z-index:9999;padding:16px;background:#fff;border-bottom:2px solid #2563eb;box-shadow:0 4px 24px rgba(0,0,0,.12);display:none;animation:slideDown .25s ease}.test-toast.show{display:block}.test-toast.pass{border-bottom-color:#059669}.test-toast.fail{border-bottom-color:#dc2626}.test-toast-header{display:flex;align-items:center;justify-content:space-between;margin-bottom:8px}.test-toast-title{font-size:15px;font-weight:700;color:#111827}.test-toast-close{border:0;background:transparent;font-size:20px;cursor:pointer;color:#6b7280;padding:0 4px}.test-toast-body{font:13px/1.7 ui-monospace,SFMono-Regular,Menlo,monospace;white-space:pre-wrap;color:#374151;max-height:260px;overflow-y:auto}@keyframes slideDown{from{transform:translateY(-100%)}to{transform:translateY(0)}}"
    "    .modal{position:fixed;inset:0;background:rgba(15,23,42,.45);display:none;align-items:center;justify-content:center;padding:16px}.modal.show{display:flex}.modal-card{width:min(420px,100%);background:#fff;border:1px solid #e5e7eb;border-radius:14px;padding:18px;box-shadow:0 20px 25px -5px rgba(0,0,0,.1),0 10px 10px -5px rgba(0,0,0,.04)}.modal-card h3{margin:0 0 8px;color:#111827}.modal-card p{margin:0 0 16px;color:#6b7280}.modal-actions{display:flex;justify-content:flex-end;gap:10px;margin-top:16px}"
    "    @media (max-width:860px){.config-grid,.grid,.agent-status-grid{grid-template-columns:1fr}}\n"
    "  </style>\n"
    "</head>\n"
    "<body>\n"
    "  <div class=\"page\">\n"
    "    <div class=\"hero\">\n"
    "      <svg class=\"hero-logo\" width=\"116\" height=\"26\" viewBox=\"0 0 116 26\" fill=\"currentColor\" xmlns=\"http://www.w3.org/2000/svg\" aria-label=\"Aiden\">"
    "<path d=\"M57.2656 8.41222C57.2656 9.76144 58.3946 10.8904 59.7438 10.8904C61.0932 10.8904 62.2219 9.76144 62.2219 8.41222C62.2219 7.063 61.0932 5.93408 59.7438 5.93408C58.3946 5.93408 57.2656 7.063 57.2656 8.41222Z\"/>"
    "<path d=\"M110.657 11.1106C113.934 11.1106 115.999 13.2858 115.999 16.6176V25.1809H114.595V16.6176C114.595 14.0844 113.135 12.4323 110.547 12.4323C107.849 12.4323 105.728 14.1945 105.728 17.9117V25.1809H104.352V11.4135H105.728V14.0293C106.775 11.9917 108.537 11.1106 110.657 11.1106Z\"/>"
    "<path d=\"M92.6825 11.1106C96.8678 11.1106 99.4835 14.58 99.4835 18.3523C99.4835 18.5725 99.456 18.7928 99.456 19.0131H86.9827C87.3132 22.1245 89.681 24.1621 92.8201 24.1621C95.0781 24.1621 96.7852 23.1158 97.5838 21.6565L98.7953 22.3724C97.6663 24.2447 95.5187 25.4838 92.7926 25.4838C88.5523 25.4838 85.5508 22.455 85.5508 18.2972C85.5508 14.2496 88.4697 11.1106 92.6825 11.1106ZM92.6825 12.4323C89.5434 12.4323 87.2582 14.6075 86.9827 17.6639H98.0518C97.7489 14.3046 95.3808 12.4323 92.6825 12.4323Z\"/>"
    "<path d=\"M79.2313 5.90649H80.608V25.1809H79.2313V21.9869C78.1023 24.1071 75.9822 25.4838 73.3114 25.4838C69.3738 25.4838 66.1797 22.3724 66.1797 18.2972C66.1797 14.222 69.3738 11.1106 73.3114 11.1106C75.9822 11.1106 78.1023 12.4873 79.2313 14.6075V5.90649ZM73.394 24.1621C76.6707 24.1621 79.2313 21.5738 79.2313 18.2972C79.2313 15.0206 76.6707 12.4323 73.394 12.4323C70.1173 12.4323 67.5566 15.0206 67.5566 18.2972C67.5566 21.5738 70.1173 24.1621 73.394 24.1621Z\"/>"
    "<path d=\"M57.6797 25.181V12.1019H61.8099V25.181H57.6797Z\"/>"
    "<path d=\"M49.7018 25.1809L48.7382 22.1521H41.5792L40.6153 25.1809H35.7969L42.3502 5.90649H47.9672L54.5205 25.1809H49.7018ZM42.9008 18.0219H47.4166L45.1586 10.9454L42.9008 18.0219Z\"/>"
    "<path d=\"M25.1178 24.5459C24.7689 25.1539 24.1252 25.524 23.426 25.524H13.692C12.7628 25.524 12.1813 24.5195 12.6413 23.7133C12.6426 23.712 12.6426 23.7093 12.6452 23.708L13.8545 21.6145H20.0426L17.6279 17.4327L18.027 16.7442L19.884 13.5272L25.1178 22.5925C25.468 23.1978 25.468 23.9432 25.1178 24.5459Z\"/>"
    "<path d=\"M15.7876 6.43232C15.3964 5.80056 14.4659 5.80981 14.0919 6.45876L12.6923 8.88403L12.3024 9.55675L5.34117 21.6143L3.64944 24.5458C3.47365 24.8471 3.22519 25.0916 2.93312 25.2621C2.64102 25.4299 2.30532 25.5238 1.95507 25.5238C1.25591 25.5238 0.61094 25.1537 0.260698 24.5458C-0.0868995 23.9417 -0.0868995 23.1976 0.260698 22.5923L10.9979 3.99781C11.3468 3.39249 11.9931 3.01978 12.6923 3.01978C13.3914 3.01978 14.0364 3.39249 14.3827 3.99781L15.7889 6.43232H15.7876Z\"/>"
    "<path d=\"M16.9459 8.43868L14.6898 12.3469L12.6914 8.88674L14.0911 6.46147C14.4651 5.81255 15.3955 5.80197 15.7868 6.43503L16.9445 8.44001L16.9459 8.43868Z\"/>"
    "<path d=\"M22.061 7.39977L19.2035 12.3481L16.9474 16.2563L13.8534 21.6156L12.6441 23.7091C12.6441 23.7091 12.6428 23.7131 12.6401 23.7144C12.1802 24.5206 12.7617 25.5251 13.6909 25.5251H9.20116C8.8443 25.5251 8.53899 25.3784 8.32093 25.151C8.29449 25.122 8.26805 25.0942 8.24295 25.0638C8.14778 24.9396 8.07246 24.8008 8.02753 24.6488C8.01959 24.6198 8.01164 24.592 8.00637 24.5629C8.00109 24.5418 7.99712 24.5193 7.99315 24.4981C7.99184 24.4902 7.99184 24.4849 7.98918 24.477C7.98787 24.4677 7.98787 24.4598 7.98787 24.4506C7.9839 24.4321 7.98257 24.4149 7.97993 24.3951C7.96277 24.1598 8.01034 23.9153 8.1425 23.688L9.3386 21.6156L14.69 12.3467L16.9461 8.4386L18.6749 5.44369C19.4176 4.15773 21.2666 4.13527 22.0398 5.40404C22.4125 6.01466 22.4204 6.78123 22.0623 7.39977H22.061Z\"/>"
    "<path d=\"M25.0995 2.27744C25.2732 1.20749 24.5466 0.19933 23.4767 0.0256534C22.4067 -0.148025 21.3986 0.578549 21.2249 1.6485C21.0512 2.71845 21.7778 3.72661 22.8477 3.90027C23.9177 4.07396 24.9258 3.3474 25.0995 2.27744Z\"/>"
    "</svg>\n"
    "      <div class=\"hero-text\">\n"
    "        <h1>配置</h1>\n"
    "        <div id=\"fwActions\" class=\"fw-actions\">\n"
    "          <p class=\"subtle\" id=\"fwVersion\"></p>\n"
    "          <button id=\"otaUpdateBtn\" class=\"button primary\" onclick=\"triggerOtaUpdate()\">OTA 更新</button>\n"
    "        </div>\n"
    "        <div id=\"fwHealth\" class=\"fw-health\"></div>\n"
    "      </div>\n"
    "    </div>\n"
    "    <div class=\"card action-card\">\n"
    "      <div id=\"actionBanner\" class=\"banner\">准备就绪。</div>\n"
    "      <div id=\"actionDetails\" class=\"details\">\n"
    "        <pre id=\"actionDetailsText\" class=\"action-detail-text\"></pre>\n"
    "        <div id=\"otaLogPanel\" class=\"ota-log-panel\">\n"
    "          <div class=\"ota-log-head\">\n"
    "            <div>\n"
    "              <div class=\"ota-log-title\">OTA 实时日志</div>\n"
    "              <div id=\"otaLogMeta\" class=\"agent-log-meta\">等待更新</div>\n"
    "            </div>\n"
    "            <button id=\"refreshOtaLogBtn\" class=\"button ghost\" onclick=\"refreshOtaLog(true)\">刷新日志</button>\n"
    "          </div>\n"
    "          <pre id=\"otaLogText\" class=\"agent-log-viewer\">点击 OTA 更新后读取日志</pre>\n"
    "        </div>\n"
    "      </div>\n"
    "    </div>\n"
    "    <div class=\"card\">\n"
    "      <div class=\"card-head\">\n"
    "        <h2>Wi-Fi 配置</h2>\n"
    "        <div class=\"toolbar\">\n"
    "          <button id=\"reloadBtn\" class=\"button ghost\" onclick=\"reloadAll()\">刷新页面数据</button>\n"
    "          <button id=\"scanBtn\" class=\"button secondary\" onclick=\"scanWifi(false)\">重新扫描</button>\n"
    "        </div>\n"
    "      </div>\n"
    "      <div id=\"wifiList\" class=\"wifi-list\"></div>\n"
    "    </div>\n"
    "    <div class=\"card\">\n"
    "      <div class=\"card-head\">\n"
    "        <h2>Agent 状态</h2>\n"
    "        <div class=\"toolbar\">\n"
    "          <button id=\"refreshAgentStatusBtn\" class=\"button ghost\" onclick=\"refreshAgentStatus(true)\">刷新状态</button>\n"
    "        </div>\n"
    "      </div>\n"
    "      <div class=\"agent-status-grid\">\n"
    "        <div class=\"agent-status-item\">\n"
    "          <span class=\"agent-status-label\">进程</span>\n"
    "          <span id=\"agentProcessStatus\" class=\"agent-status-value\">读取中</span>\n"
    "          <div id=\"agentProcessDetail\" class=\"agent-status-detail\"></div>\n"
    "        </div>\n"
    "        <div class=\"agent-status-item\">\n"
    "          <span class=\"agent-status-label\">端口</span>\n"
    "          <span id=\"agentPortStatus\" class=\"agent-status-value\">读取中</span>\n"
    "          <div id=\"agentPortDetail\" class=\"agent-status-detail\"></div>\n"
    "        </div>\n"
    "      </div>\n"
    "      <div id=\"agentStartupError\" class=\"details\">\n"
    "        <pre id=\"agentStartupErrorText\"></pre>\n"
    "      </div>\n"
    "      <div class=\"agent-log-head\">\n"
    "        <div>\n"
    "          <h3>Agent 实时日志</h3>\n"
    "          <div id=\"agentLogMeta\" class=\"agent-log-meta\">读取中</div>\n"
    "        </div>\n"
    "        <div class=\"toolbar\">\n"
    "          <button id=\"pauseAgentLogBtn\" class=\"button ghost\" onclick=\"toggleAgentLogPause()\">暂停</button>\n"
    "          <button id=\"refreshAgentLogBtn\" class=\"button ghost\" onclick=\"refreshAgentLog(true)\">刷新日志</button>\n"
    "        </div>\n"
    "      </div>\n"
    "      <pre id=\"agentLogText\" class=\"agent-log-viewer\">读取中</pre>\n"
    "    </div>\n"
    "    <div class=\"card\">\n"
    "      <div class=\"card-head\">\n"
    "        <h2>Agent 配置</h2>\n"
    "      </div>\n"
    "      <div class=\"config-grid\">\n"
    "        <div class=\"section-card\" id=\"section-agent\">\n"
    "          <div class=\"card-head\">\n"
    "            <h3>[agent]</h3>\n"
    "            <div class=\"section-actions\">\n"
    "              <button class=\"button ghost edit-btn\" onclick=\"enterEditSection('agent')\">编辑</button>\n"
    "              <button class=\"button secondary\" onclick=\"testSection('agent')\">测试</button>\n"
    "              <button class=\"button ghost cancel-btn\" onclick=\"cancelEditSection('agent')\">取消</button>\n"
    "              <button id=\"save-agent\" class=\"button primary save-btn\" onclick=\"saveSection('agent')\">保存</button>\n"
    "            </div>\n"
    "          </div>\n"
    "          <div class=\"grid\">\n"
    "            <div class=\"field\"><label>input_mode</label><select id=\"agent_input_mode\" data-section=\"agent\"></select></div>\n"
    "            <div class=\"field\"><label>trigger_mode</label><select id=\"agent_trigger_mode\" data-section=\"agent\"></select></div>\n"
    "            <div class=\"field\"><label>vad_backend</label><select id=\"agent_vad_backend\" data-section=\"agent\"></select></div>\n"
    "            <div class=\"field wide\"><label>vad_model_path</label><input id=\"agent_vad_model_path\" data-section=\"agent\"></div>\n"
    "            <div class=\"field wide\"><label>vad_helper_path</label><input id=\"agent_vad_helper_path\" data-section=\"agent\"></div>\n"
    "            <div class=\"field\"><label>vad_speech_threshold</label><select id=\"agent_vad_speech_threshold\" data-section=\"agent\"></select></div>\n"
    "            <div class=\"field\"><label>silence_ms</label><input id=\"agent_silence_ms\" type=\"number\" data-section=\"agent\"></div>\n"
    "            <div class=\"field\"><label>min_speech_ms</label><input id=\"agent_min_speech_ms\" type=\"number\" data-section=\"agent\"></div>\n"
    "            <div class=\"field\"><label>voice_followup_enabled</label><input id=\"agent_voice_followup_enabled\" type=\"checkbox\" data-section=\"agent\"></div>\n"
    "            <div class=\"field\"><label>voice_followup_timeout_ms</label><input id=\"agent_voice_followup_timeout_ms\" type=\"number\" data-section=\"agent\"></div>\n"
    "            <div class=\"field\"><label>voice_first_turn_timeout_ms</label><input id=\"agent_voice_first_turn_timeout_ms\" type=\"number\" data-section=\"agent\"></div>\n"
    "            <div class=\"field\"><label>voice_max_turns</label><input id=\"agent_voice_max_turns\" type=\"number\" data-section=\"agent\"></div>\n"
    "            <div class=\"field\"><label>voice_interrupt_on_wakeup</label><input id=\"agent_voice_interrupt_on_wakeup\" type=\"checkbox\" data-section=\"agent\"></div>\n"
    "            <div class=\"field\"><label>voice_streaming_tts_enabled</label><input id=\"agent_voice_streaming_tts_enabled\" type=\"checkbox\" data-section=\"agent\"></div>\n"
    "            <div class=\"field\"><label>voice_tool_call_speech</label><input id=\"agent_voice_tool_call_speech\" type=\"checkbox\" data-section=\"agent\"></div>\n"
    "            <div class=\"field\"><label>voice_progress_speech_enabled</label><input id=\"agent_voice_progress_speech_enabled\" type=\"checkbox\" data-section=\"agent\"></div>\n"
    "            <div class=\"field\"><label>voice_speech_summary_enabled</label><input id=\"agent_voice_speech_summary_enabled\" type=\"checkbox\" data-section=\"agent\"></div>\n"
    "            <div class=\"field\"><label>voice_max_response_tokens</label><input id=\"agent_voice_max_response_tokens\" type=\"number\" data-section=\"agent\"></div>\n"
    "            <div class=\"field\"><label>max_iterations</label><input id=\"agent_max_iterations\" type=\"number\" data-section=\"agent\"></div>\n"
    "            <div class=\"field\"><label>force_simple_loop</label><input id=\"agent_force_simple_loop\" type=\"checkbox\" data-section=\"agent\"></div>\n"
    "            <div class=\"field\"><label>screenshot_keep_n</label><input id=\"agent_screenshot_keep_n\" type=\"number\" data-section=\"agent\"></div>\n"
    "            <div class=\"field\"><label>screenshot_prune_interval</label><input id=\"agent_screenshot_prune_interval\" type=\"number\" data-section=\"agent\"></div>\n"
    "            <div class=\"field\"><label>screen_stable_timeout_ms</label><input id=\"agent_screen_stable_timeout_ms\" type=\"number\" data-section=\"agent\"></div>\n"
    "            <div class=\"field\"><label>screen_stable_ms</label><input id=\"agent_screen_stable_ms\" type=\"number\" data-section=\"agent\"></div>\n"
    "            <div class=\"field\"><label>screen_stable_diff_threshold</label><input id=\"agent_screen_stable_diff_threshold\" type=\"number\" step=\"0.1\" data-section=\"agent\"></div>\n"
    "            <div class=\"field wide\"><label>custom_instruction</label><textarea id=\"agent_custom_instruction\" data-section=\"agent\"></textarea></div>\n"
    "            <div class=\"field wide\"><label>additional_prompt</label><textarea id=\"agent_additional_prompt\" data-section=\"agent\"></textarea></div>\n"
    "          </div>\n"
    "        </div>\n"
    "        <div class=\"section-card\" id=\"section-model\">\n"
    "          <div class=\"card-head\">\n"
    "            <h3>[model]</h3>\n"
    "            <div class=\"section-actions\">\n"
    "              <button class=\"button ghost edit-btn\" onclick=\"enterEditSection('model')\">编辑</button>\n"
    "              <button class=\"button secondary\" onclick=\"testSection('model')\">测试</button>\n"
    "              <button class=\"button ghost cancel-btn\" onclick=\"cancelEditSection('model')\">取消</button>\n"
    "              <button id=\"save-model\" class=\"button primary save-btn\" onclick=\"saveSection('model')\">保存</button>\n"
    "            </div>\n"
    "          </div>\n"
    "          <div class=\"grid\">\n"
    "            <div class=\"field\"><label>provider</label><select id=\"model_provider\" data-section=\"model\"></select></div>\n"
    "            <div class=\"field\"><label>token_env</label><input id=\"model_token_env\" data-section=\"model\"></div>\n"
    "            <div class=\"field wide\"><label>model</label><input id=\"model_model\" data-section=\"model\"></div>\n"
    "            <div class=\"field wide\"><label>api_key</label><input id=\"model_api_key\" data-section=\"model\"></div>\n"
    "            <div class=\"field wide\"><label>base_url</label><input id=\"model_base_url\" data-section=\"model\"></div>\n"
    "            <div class=\"field\"><label>temperature</label><input id=\"model_temperature\" type=\"number\" step=\"0.1\" data-section=\"model\"></div>\n"
    "            <div class=\"field\"><label>max_response_tokens</label><input id=\"model_max_response_tokens\" type=\"number\" data-section=\"model\"></div>\n"
    "            <div class=\"field\"><label>context_window</label><input id=\"model_context_window\" type=\"number\" data-section=\"model\" placeholder=\"0 = auto\" title=\"0 = auto: use provider metadata when available\"><div class=\"field-hint\">0 = auto: use provider metadata when available.</div></div>\n"
    "            <div class=\"field\"><label>model_max_output_tokens</label><input id=\"model_model_max_output_tokens\" type=\"number\" data-section=\"model\" placeholder=\"0 = auto\" title=\"0 = auto: use provider metadata when available\"></div>\n"
    "          </div>\n"
    "        </div>\n"
    "        <div class=\"section-card\" id=\"section-tts\">\n"
    "          <div class=\"card-head\">\n"
    "            <h3>[tts]</h3>\n"
    "            <div class=\"section-actions\">\n"
    "              <button class=\"button ghost edit-btn\" onclick=\"enterEditSection('tts')\">编辑</button>\n"
    "              <button class=\"button secondary\" onclick=\"testSection('tts')\">测试</button>\n"
    "              <button class=\"button ghost cancel-btn\" onclick=\"cancelEditSection('tts')\">取消</button>\n"
    "              <button id=\"save-tts\" class=\"button primary save-btn\" onclick=\"saveSection('tts')\">保存</button>\n"
    "            </div>\n"
    "          </div>\n"
    "          <div class=\"grid\">\n"
    "            <div class=\"field\"><label>provider</label><select id=\"tts_provider\" data-section=\"tts\"></select></div>\n"
    "            <div class=\"field\"><label>speed</label><select id=\"tts_speed\" data-section=\"tts\"></select></div>\n"
    "            <div class=\"field wide\"><label>api_key</label><input id=\"tts_api_key\" data-section=\"tts\"></div>\n"
    "            <div class=\"field wide\"><label>model</label><input id=\"tts_model\" data-section=\"tts\"></div>\n"
    "            <div class=\"field\"><label>voice_id</label><input id=\"tts_voice_id\" data-section=\"tts\"></div>\n"
    "            <div class=\"field\"><label>emotion</label><input id=\"tts_emotion\" data-section=\"tts\"></div>\n"
    "          </div>\n"
    "        </div>\n"
    "        <div class=\"section-card\" id=\"section-stt\">\n"
    "          <div class=\"card-head\">\n"
    "            <h3>[stt]</h3>\n"
    "            <div class=\"section-actions\">\n"
    "              <button class=\"button ghost edit-btn\" onclick=\"enterEditSection('stt')\">编辑</button>\n"
    "              <button class=\"button secondary\" onclick=\"testSection('stt')\">测试</button>\n"
    "              <button class=\"button ghost cancel-btn\" onclick=\"cancelEditSection('stt')\">取消</button>\n"
    "              <button id=\"save-stt\" class=\"button primary save-btn\" onclick=\"saveSection('stt')\">保存</button>\n"
    "            </div>\n"
    "          </div>\n"
    "          <div class=\"grid\">\n"
    "            <div class=\"field\"><label>provider</label><select id=\"stt_provider\" data-section=\"stt\"></select></div>\n"
    "            <div class=\"field\"><label>region</label><input id=\"stt_region\" data-section=\"stt\"></div>\n"
    "            <div class=\"field wide\"><label>api_key</label><input id=\"stt_api_key\" data-section=\"stt\"></div>\n"
    "            <div class=\"field wide\"><label>model</label><input id=\"stt_model\" data-section=\"stt\"></div>\n"
    "            <div class=\"field wide\"><label>base_url</label><input id=\"stt_base_url\" data-section=\"stt\"></div>\n"
    "            <div class=\"field\"><label>secret_id</label><input id=\"stt_secret_id\" data-section=\"stt\"></div>\n"
    "            <div class=\"field\"><label>secret_key</label><input id=\"stt_secret_key\" data-section=\"stt\"></div>\n"
    "            <div class=\"field wide\"><label>engine_model_type</label><input id=\"stt_engine_model_type\" data-section=\"stt\"></div>\n"
    "          </div>\n"
    "        </div>\n"
    "        <div class=\"section-card\" id=\"section-audio\">\n"
    "          <div class=\"card-head\">\n"
    "            <h3>[audio]</h3>\n"
    "            <div class=\"section-actions\">\n"
    "              <button class=\"button ghost edit-btn\" onclick=\"enterEditSection('audio')\">编辑</button>\n"
    "              <button class=\"button secondary\" onclick=\"testSection('audio')\">测试</button>\n"
    "              <button class=\"button ghost cancel-btn\" onclick=\"cancelEditSection('audio')\">取消</button>\n"
    "              <button id=\"save-audio\" class=\"button primary save-btn\" onclick=\"saveSection('audio')\">保存</button>\n"
    "            </div>\n"
    "          </div>\n"
    "          <div class=\"grid\">\n"
    "            <div class=\"field wide\"><label>socket</label><input id=\"audio_socket\" data-section=\"audio\"></div>\n"
    "            <div class=\"field\"><label>sample_rate</label><input id=\"audio_sample_rate\" type=\"number\" data-section=\"audio\"></div>\n"
    "            <div class=\"field\"><label>channels</label><input id=\"audio_channels\" type=\"number\" data-section=\"audio\"></div>\n"
    "            <div class=\"field\"><label>bit_width</label><input id=\"audio_bit_width\" type=\"number\" data-section=\"audio\"></div>\n"
    "          </div>\n"
    "        </div>\n"
    "        <div class=\"section-card\" id=\"section-audio_archive\">\n"
    "          <div class=\"card-head\">\n"
    "            <h3>[audio_archive]</h3>\n"
    "            <div class=\"section-actions\">\n"
    "              <button class=\"button ghost edit-btn\" onclick=\"enterEditSection('audio_archive')\">编辑</button>\n"
    "              <button class=\"button ghost cancel-btn\" onclick=\"cancelEditSection('audio_archive')\">取消</button>\n"
    "              <button id=\"save-audio_archive\" class=\"button primary save-btn\" onclick=\"saveSection('audio_archive')\">保存</button>\n"
    "            </div>\n"
    "          </div>\n"
    "          <div id=\"audioArchiveModeHint\" class=\"field-hint section-note\">仅在 agent.input_mode = stt 时生效；切到 STT 后可编辑录音保存设置。</div>\n"
    "          <div class=\"grid\">\n"
    "            <div class=\"field\"><label>enabled</label><input id=\"audio_archive_enabled\" type=\"checkbox\" data-section=\"audio_archive\"><div class=\"field-hint\">开启后保存 STT 语音录音 WAV，用于 Web UI 播放；超过数量或容量上限时自动删除旧文件。</div></div>\n"
    "            <div class=\"field wide\"><label>storage_path</label><input id=\"audio_archive_storage_path\" data-section=\"audio_archive\"></div>\n"
    "            <div class=\"field\"><label>max_files</label><input id=\"audio_archive_max_files\" type=\"number\" data-section=\"audio_archive\"></div>\n"
    "            <div class=\"field\"><label>max_size_mb</label><input id=\"audio_archive_max_size_mb\" type=\"number\" data-section=\"audio_archive\"></div>\n"
    "          </div>\n"
    "        </div>\n"
    "        <div class=\"section-card\" id=\"section-benchmark\">\n"
    "          <div class=\"card-head\">\n"
    "            <h3>[benchmark]</h3>\n"
    "            <div class=\"section-actions\">\n"
    "              <button class=\"button ghost edit-btn\" onclick=\"enterEditSection('benchmark')\">编辑</button>\n"
    "              <button class=\"button secondary\" onclick=\"testSection('benchmark')\">测试</button>\n"
    "              <button class=\"button ghost cancel-btn\" onclick=\"cancelEditSection('benchmark')\">取消</button>\n"
    "              <button id=\"save-benchmark\" class=\"button primary save-btn\" onclick=\"saveSection('benchmark')\">保存</button>\n"
    "            </div>\n"
    "          </div>\n"
    "          <div class=\"grid\">\n"
    "            <div class=\"field wide\"><label>judge_model</label><input id=\"benchmark_judge_model\" data-section=\"benchmark\" placeholder=\"empty = bytedance-seed/seed-2.0-lite\"></div>\n"
    "            <div class=\"field wide\"><label>api_key</label><input id=\"benchmark_api_key\" type=\"password\" autocomplete=\"off\" data-section=\"benchmark\"></div>\n"
    "            <div class=\"field wide\"><label>benchmark_dir</label><input id=\"benchmark_benchmark_dir\" data-section=\"benchmark\" placeholder=\"empty = auto-detect benchmark root\"></div>\n"
    "          </div>\n"
    "        </div>\n"
    "        <div class=\"section-card\" id=\"section-hid\">\n"
    "          <div class=\"card-head\">\n"
    "            <h3>[hid]</h3>\n"
    "            <div class=\"section-actions\">\n"
    "              <button class=\"button ghost edit-btn\" onclick=\"enterEditSection('hid')\">编辑</button>\n"
    "              <button class=\"button secondary\" onclick=\"testSection('hid')\">测试</button>\n"
    "              <button class=\"button ghost cancel-btn\" onclick=\"cancelEditSection('hid')\">取消</button>\n"
    "              <button id=\"save-hid\" class=\"button primary save-btn\" onclick=\"saveSection('hid')\">保存</button>\n"
    "            </div>\n"
    "          </div>\n"
    "          <div class=\"grid\">\n"
    "            <div class=\"field\"><label>pointer_mode</label><select id=\"hid_pointer_mode\" data-section=\"hid\"></select></div>\n"
    "            <div class=\"field wide\"><label>keyboard_device</label><input id=\"hid_keyboard_device\" data-section=\"hid\"></div>\n"
    "            <div class=\"field wide\"><label>mouse_device</label><input id=\"hid_mouse_device\" data-section=\"hid\"></div>\n"
    "            <div class=\"field wide\"><label>frame_socket</label><input id=\"hid_frame_socket\" data-section=\"hid\"></div>\n"
    "          </div>\n"
    "        </div>\n"
    "        <div class=\"section-card\" id=\"section-system_env\">\n"
    "          <div class=\"card-head\">\n"
    "            <h3>env</h3>\n"
    "            <div class=\"section-actions\">\n"
    "              <button class=\"button ghost edit-btn\" onclick=\"enterSystemEnvEdit()\">编辑</button>\n"
    "              <button class=\"button ghost cancel-btn\" onclick=\"cancelSystemEnvEdit()\">取消</button>\n"
    "              <button id=\"save-system_env\" class=\"button primary save-btn\" onclick=\"saveSystemEnv()\">保存</button>\n"
    "            </div>\n"
    "          </div>\n"
    "          <div class=\"grid\">\n"
    "            <div class=\"field wide\"><label>/userdata/system/env</label><textarea id=\"system_env_content\" data-section=\"system_env\" spellcheck=\"false\"></textarea></div>\n"
    "          </div>\n"
    "        </div>\n"
    "        <div class=\"section-card\" id=\"section-search\">\n"
    "          <div class=\"card-head\">\n"
    "            <h3>[search]</h3>\n"
    "            <div class=\"section-actions\">\n"
    "              <button class=\"button ghost edit-btn\" onclick=\"enterEditSection('search')\">编辑</button>\n"
    "              <button class=\"button secondary\" onclick=\"testSection('search')\">测试</button>\n"
    "              <button class=\"button ghost cancel-btn\" onclick=\"cancelEditSection('search')\">取消</button>\n"
    "              <button id=\"save-search\" class=\"button primary save-btn\" onclick=\"saveSection('search')\">保存</button>\n"
    "            </div>\n"
    "          </div>\n"
    "          <div class=\"grid\">\n"
    "            <div class=\"field\"><label>provider</label><select id=\"search_provider\" data-section=\"search\"></select></div>\n"
    "            <div class=\"field wide\"><label>api_key</label><input id=\"search_api_key\" type=\"password\" autocomplete=\"off\" data-section=\"search\"></div>\n"
    "          </div>\n"
    "        </div>\n"
    "        <div class=\"section-card\" id=\"section-telemetry\">\n"
    "          <div class=\"card-head\">\n"
    "            <h3>[telemetry]</h3>\n"
    "            <div class=\"section-actions\">\n"
    "              <button class=\"button ghost edit-btn\" onclick=\"enterEditSection('telemetry')\">编辑</button>\n"
    "              <button class=\"button secondary\" onclick=\"testSection('telemetry')\">测试</button>\n"
    "              <button class=\"button ghost cancel-btn\" onclick=\"cancelEditSection('telemetry')\">取消</button>\n"
    "              <button id=\"save-telemetry\" class=\"button primary save-btn\" onclick=\"saveSection('telemetry')\">保存</button>\n"
    "            </div>\n"
    "          </div>\n"
    "          <div class=\"grid\">\n"
    "            <div class=\"field\"><label>enabled</label><input id=\"telemetry_enabled\" type=\"checkbox\" data-section=\"telemetry\"></div>\n"
    "            <div class=\"field\"><label>provider</label><select id=\"telemetry_provider\" data-section=\"telemetry\"></select></div>\n"
    "            <div class=\"field wide\"><label>base_url</label><input id=\"telemetry_base_url\" data-section=\"telemetry\" placeholder=\"http://langfuse.example.com:3000\"></div>\n"
    "            <div class=\"field wide\"><label>public_key</label><input id=\"telemetry_public_key\" type=\"password\" autocomplete=\"off\" data-section=\"telemetry\"></div>\n"
    "            <div class=\"field wide\"><label>secret_key</label><input id=\"telemetry_secret_key\" type=\"password\" autocomplete=\"off\" data-section=\"telemetry\"></div>\n"
    "            <div class=\"field\"><label>upload_screenshots</label><input id=\"telemetry_upload_screenshots\" type=\"checkbox\" data-section=\"telemetry\"></div>\n"
    "            <div class=\"field\"><label>upload_timeout_sec</label><input id=\"telemetry_upload_timeout_sec\" type=\"number\" data-section=\"telemetry\"></div>\n"
    "            <div class=\"field\"><label>max_retry</label><input id=\"telemetry_max_retry\" type=\"number\" data-section=\"telemetry\"></div>\n"
    "            <div class=\"field\"><label>environment</label><input id=\"telemetry_environment\" data-section=\"telemetry\"></div>\n"
    "            <div class=\"field wide\"><label>tags</label><textarea id=\"telemetry_tags\" data-section=\"telemetry\" spellcheck=\"false\"></textarea></div>\n"
    "          </div>\n"
    "        </div>\n"
    "      </div>\n"
    "    </div>\n"
    "  </div>\n"
    "  <div id=\"testToast\" class=\"test-toast\"><div class=\"test-toast-header\"><span class=\"test-toast-title\" id=\"testToastTitle\"></span><button class=\"test-toast-close\" onclick=\"closeTestToast()\">&times;</button></div><div class=\"test-toast-body\" id=\"testToastBody\"></div></div>\n"
    "  <div id=\"wifiModal\" class=\"modal\">\n"
    "    <div class=\"modal-card\">\n"
    "      <h3>连接 Wi-Fi</h3>\n"
    "      <p id=\"wifiModalText\">选择的网络</p>\n"
    "      <div class=\"field\">\n"
    "        <label>密码</label>\n"
    "        <input id=\"wifiPasswordInput\" type=\"password\" placeholder=\"开放网络可留空\">\n"
    "      </div>\n"
    "      <div class=\"modal-actions\">\n"
    "        <button class=\"button ghost\" onclick=\"closeWifiModal()\">取消</button>\n"
    "        <button id=\"connectWifiBtn\" class=\"button primary\" onclick=\"connectSelectedWifi()\">连接</button>\n"
    "      </div>\n"
    "    </div>\n"
    "  </div>\n"
    "  <script>\n"
    "    function rangeOptions(start,end,step,precision){const values=[];for(let i=0,n=start;n<=end+step/2;i++,n=start+i*step){values.push(String(Number(n.toFixed(precision))));}return values;}\n"
    "    let configMeta=null;let sectionFields={};let selectFieldOptions={};let fieldDefaults={};let visibilityRules=[];let watchedFields=[];\n"
    "    function widgetValueType(field){const w=field.widget;if(w==='boolean')return 'boolean';if(w==='list')return 'list';if(w==='number')return 'number';if(w==='select')return field.range?'number':'text';return 'text';}\n"
    "    function collectWatched(rule,watched){const conds=[].concat(rule.all||[],rule.any||[]);conds.forEach(function(c){if(c.field)watched[c.field]=true;});}\n"
    "    function formatDefaultValue(value){if(Array.isArray(value))return value.join(', ');if(value===true)return 'true';if(value===false)return 'false';if(value==null)return '';return String(value);}\n"
    "    function fieldDefaultPlaceholder(value){const text=formatDefaultValue(value);const shown=text===''?'空':(text.length>120?text.slice(0,117)+'...':text);return '默认值: '+shown;}\n"
    "    function applyDefaultPlaceholder(section,field){if(field.default===undefined||field.secret)return;const el=byId(section+'_'+field.key);if(!el||el.type==='checkbox'||el.tagName==='SELECT')return;if(el.getAttribute('placeholder'))return;el.setAttribute('placeholder',fieldDefaultPlaceholder(field.default));}\n"
    "    function buildConfigMeta(meta){configMeta=meta;sectionFields={};selectFieldOptions={};fieldDefaults={};visibilityRules=[];const watched={};(meta.sections||[]).forEach(function(section){const name=section.name;sectionFields[name]=[];selectFieldOptions[name]=selectFieldOptions[name]||{};fieldDefaults[name]=fieldDefaults[name]||{};(section.fields||[]).forEach(function(field){sectionFields[name].push([field.key,widgetValueType(field)]);if(field.default!==undefined){fieldDefaults[name][field.key]=field.default;applyDefaultPlaceholder(name,field);}if(field.widget==='select'){let opts=[];if(field.range){opts=rangeOptions(field.range.min,field.range.max,field.range.step,field.range.precision||0);}else if(field.enum){opts=field.enum.map(function(o){return o.label?[o.value,o.label]:o.value;});}selectFieldOptions[name][field.key]=opts;}if(field.secret){const sel=byId(name+'_'+field.key);if(sel&&sel.tagName==='INPUT'){sel.type='password';sel.setAttribute('autocomplete','off');}}if(field.visibleWhen){visibilityRules.push({section:name,key:field.key,rule:field.visibleWhen});collectWatched(field.visibleWhen,watched);}});});watchedFields=Object.keys(watched);}\n"
    "    function evalCondition(cond){const parts=String(cond.field||'').split('.');const val=fieldValue(parts[0],parts.slice(1).join('.'));const op=cond.op;if(op==='truthy')return !!val;const s=String(val==null?'':val);if(op==='eq')return s===String(cond.value);if(op==='ne')return s!==String(cond.value);if(op==='in')return (cond.values||[]).indexOf(s)>=0;if(op==='notIn')return (cond.values||[]).indexOf(s)<0;return true;}\n"
    "    function evalRule(rule){if(rule.all)return rule.all.every(evalCondition);if(rule.any)return rule.any.some(evalCondition);return true;}\n"
    "    const appState={config:null,wifi:null,wifiStatus:null,agentStatus:null,agentLog:null,agentLogPaused:false,otaLog:null,otaLogVisible:false,otaLogPending:false,otaLogStartSize:0,systemEnv:'',networks:[],selectedSsid:'',wifiListExpanded:false};\n"
    "    const sectionSnapshots={};\n"
    "    let systemEnvSnapshot='';\n"
    "    function byId(id){return document.getElementById(id);}\n"
    "    function optionValue(option){return Array.isArray(option)?String(option[0]):String(option);}\n"
    "    function optionLabel(option){return Array.isArray(option)?String(option[1]):String(option);}\n"
    "    function addSelectOption(el,value,label){const option=document.createElement('option');option.value=value;option.textContent=label;el.appendChild(option);}\n"
    "    function hydrateSelectOptions(){Object.keys(selectFieldOptions).forEach(function(section){const fields=selectFieldOptions[section];Object.keys(fields).forEach(function(key){const el=byId(section+'_'+key);if(!el||el.tagName!=='SELECT')return;el.innerHTML='';fields[key].forEach(function(option){addSelectOption(el,optionValue(option),optionLabel(option));});});});}\n"
    "    function ensureSelectOption(el,value){if(!el||el.tagName!=='SELECT')return;const normalized=value==null?'':String(value);if(normalized==='')return;for(let i=0;i<el.options.length;i++){if(el.options[i].value===normalized)return;}addSelectOption(el,normalized,normalized);}\n"
    "    function setFieldVisible(section,key,visible){const el=byId(section+'_'+key);if(!el)return;const field=el.closest?el.closest('.field'):el.parentNode;if(!field)return;if(visible){field.classList.remove('hidden');}else{field.classList.add('hidden');}}\n"
    "    function fieldValue(section,key){const el=byId(section+'_'+key);if(!el)return '';return el.type==='checkbox'?!!el.checked:el.value;}\n"
    "    function applyFieldVisibility(){visibilityRules.forEach(function(r){setFieldVisible(r.section,r.key,evalRule(r.rule));});applyAudioArchiveAvailability();}\n"
    "    function bindFieldVisibility(){watchedFields.forEach(function(path){const parts=path.split('.');const el=byId(parts[0]+'_'+parts.slice(1).join('.'));if(el){el.addEventListener('change',function(){applyFieldVisibility();});}});}\n"
    "    function setBanner(message,isError){const el=byId('actionBanner');el.textContent=message;el.className='banner'+(isError?' error':'');}\n"
    "    function updateActionDetailsVisibility(){const wrap=byId('actionDetails');const body=byId('actionDetailsText');const ota=byId('otaLogPanel');const hasText=!!(body&&body.style.display!=='none'&&body.textContent);const hasOta=!!(ota&&ota.style.display!=='none');wrap.style.display=(hasText||hasOta)?'block':'none';}\n"
    "    function hideOtaLogPanel(){const panel=byId('otaLogPanel');if(panel){panel.style.display='none';}appState.otaLogVisible=false;appState.otaLogPending=false;updateActionDetailsVisibility();}\n"
    "    function setDetails(text,options){const body=byId('actionDetailsText');if(!(options&&options.keepOtaLog)){hideOtaLogPanel();}if(text){body.style.display='block';body.textContent=text;}else{body.style.display='none';body.textContent='';}updateActionDetailsVisibility();}\n"
    "    async function request(url,options){const res=await fetch(url,options);const text=await res.text();let body={};try{body=text?JSON.parse(text):{}}catch(err){body={ok:false,error:text||err.message}}if(!res.ok){throw new Error(body.error||('HTTP '+res.status))}return body;}\n"
    "    function isAudioArchiveAvailable(){return fieldValue('agent','input_mode')==='stt';}\n"
    "    function sectionModeLocked(section){return section==='audio_archive'&&!isAudioArchiveAvailable();}\n"
    "    function setAudioArchiveActionState(locked){const card=byId('section-audio_archive');if(!card)return;card.querySelectorAll('.edit-btn,.section-actions .secondary').forEach(function(btn){btn.disabled=locked;});}\n"
    "    function applyAudioArchiveAvailability(){const card=byId('section-audio_archive');if(!card)return;const available=isAudioArchiveAvailable();const hint=byId('audioArchiveModeHint');card.classList.toggle('mode-locked',!available);if(hint){hint.textContent=available?'STT 模式下会保存唤醒后的语音录音，供历史记录播放。':'仅在 agent.input_mode = stt 时生效；切到 STT 后可编辑录音保存设置。';}setAudioArchiveActionState(!available);if(!available){delete sectionSnapshots.audio_archive;card.classList.remove('editing');setSectionLocked('audio_archive',true);}}\n"
    "    function setSectionLocked(section,locked){const actualLocked=locked||sectionModeLocked(section);document.querySelectorAll('[data-section='+section+']').forEach(function(el){el.disabled=actualLocked;});const btn=byId('save-'+section);if(btn)btn.disabled=actualLocked;}\n"
    "    function setSystemEnvLocked(locked){byId('system_env_content').disabled=locked;byId('save-system_env').disabled=locked;}\n"
    "    function lockAllSections(){Object.keys(sectionFields).forEach(function(section){setSectionLocked(section,true);const card=byId('section-'+section);if(card)card.classList.remove('editing');});setSystemEnvLocked(true);byId('section-system_env').classList.remove('editing');}\n"
    "    function enterEditSection(section){if(sectionModeLocked(section)){setBanner('['+section+'] 仅在 agent.input_mode = stt 时可编辑。',false);setDetails('先在 [agent] 中把 input_mode 改为 stt 并保存。');return;}const snap={};sectionFields[section].forEach(function(item){const el=byId(section+'_'+item[0]);if(!el)return;snap[item[0]]=item[1]==='boolean'?el.checked:el.value;});sectionSnapshots[section]=snap;setSectionLocked(section,false);byId('section-'+section).classList.add('editing');setBanner('正在编辑 ['+section+']，改完后点保存。',false);setDetails('');}\n"
    "    function cancelEditSection(section){const snap=sectionSnapshots[section]||{};sectionFields[section].forEach(function(item){const el=byId(section+'_'+item[0]);if(!el)return;if(snap[item[0]]!==undefined){if(item[1]==='boolean')el.checked=!!snap[item[0]];else el.value=snap[item[0]];}});applyFieldVisibility();delete sectionSnapshots[section];setSectionLocked(section,true);byId('section-'+section).classList.remove('editing');setBanner('已取消 ['+section+'] 的修改。',false);setDetails('');}\n"
    "    function enterSystemEnvEdit(){systemEnvSnapshot=byId('system_env_content').value;setSystemEnvLocked(false);byId('section-system_env').classList.add('editing');setBanner('正在编辑 env，改完后点保存。',false);setDetails('');}\n"
    "    function cancelSystemEnvEdit(){byId('system_env_content').value=systemEnvSnapshot;setSystemEnvLocked(true);byId('section-system_env').classList.remove('editing');setBanner('已取消 env 的修改。',false);setDetails('');}\n"
    "    function formatListValue(value){return Array.isArray(value)?value.join('\\n'):(value==null?'':String(value));}\n"
    "    function parseListValue(value){return String(value||'').split(/[\\n,]/).map(function(v){return v.trim();}).filter(Boolean);}\n"
    "    function setFieldValue(section,key,value){const el=byId(section+'_'+key);if(!el)return;if(el.type==='password'){const sectionValues=(appState.config&&appState.config[section])||{};const hasKey=!!value||!!sectionValues['has_'+key];el.value='';el.placeholder=hasKey?'已保存；留空则保持不变':'未设置';return;}if(el.type==='checkbox')el.checked=!!value;else if(Array.isArray(value))el.value=formatListValue(value);else{const text=value==null?'':String(value);ensureSelectOption(el,text);el.value=text;}}\n"
    "    function fillConfigForm(config){Object.keys(sectionFields).forEach(function(section){const values=config[section]||{};sectionFields[section].forEach(function(item){setFieldValue(section,item[0],values[item[0]]);});});applyFieldVisibility();}\n"
    "    function readSection(section){const values=Object.assign({},(appState.config&&appState.config[section])||{});sectionFields[section].forEach(function(item){const key=item[0];const type=item[1];const el=byId(section+'_'+key);if(!el)return;const raw=el.value;if(el.type==='password'&&raw===''){return;}if(type==='number'){values[key]=raw===''?0:Number(raw);}else if(type==='boolean'){values[key]=!!el.checked;}else if(type==='list'){values[key]=parseListValue(raw);}else{values[key]=raw;}});return values;}\n"
    "    function setAgentStatusValue(id,text,tone){const el=byId(id);el.textContent=text;el.className='agent-status-value '+tone;}\n"
    "    function agentStateText(state){const names={running:'运行中',starting:'启动中',error:'启动失败',stopped:'未运行',port_unreachable:'端口未连通',unknown:'未知'};return names[state]||state||'未知';}\n"
    "    function renderAgentStatus(status){status=status||{};appState.agentStatus=status;const state=status.state||'unknown';let processText=agentStateText(state);if(status.process_running&&status.pid){processText+=' · PID '+status.pid;}let processTone=(state==='running')?'ok':((state==='starting'||state==='port_unreachable')?'warn':'error');setAgentStatusValue('agentProcessStatus',processText,processTone);let processDetail=[];if(status.watchdog_running){processDetail.push('watchdog PID '+(status.watchdog_pid||''));}else{processDetail.push('watchdog stopped');}if(status.detail){processDetail.push(status.detail);}byId('agentProcessDetail').textContent=processDetail.filter(Boolean).join('\\n');const host=status.port_host||'127.0.0.1';const port=status.port||8080;const portText=host+':'+port+' · '+(status.port_reachable?'可连接':'不可连接');setAgentStatusValue('agentPortStatus',portText,status.port_reachable?'ok':'error');byId('agentPortDetail').textContent=status.port_detail||'';const err=status.startup_error||'';byId('agentStartupError').style.display=err?'block':'none';byId('agentStartupErrorText').textContent=err?'最近启动日志：\\n'+err:'';}\n"
    "    async function refreshAgentStatus(showBanner){const btn=byId('refreshAgentStatusBtn');if(btn)btn.disabled=true;try{const payload=await request('/api/agent/status',{method:'GET'});renderAgentStatus(payload.agent_status||{});if(showBanner){setBanner('Agent 状态已刷新。',false);}}catch(err){setAgentStatusValue('agentProcessStatus','读取失败','error');setAgentStatusValue('agentPortStatus','读取失败','error');byId('agentProcessDetail').textContent=err.message;if(showBanner){setBanner('刷新 Agent 状态失败。',true);setDetails(err.message);}}finally{if(btn)btn.disabled=false;}}\n"
    "    function formatLogSize(bytes){bytes=Number(bytes||0);if(bytes<1024)return bytes+' B';if(bytes<1048576)return (bytes/1024).toFixed(1)+' KB';return (bytes/1048576).toFixed(1)+' MB';}\n"
    "    function renderAgentLog(snapshot){snapshot=snapshot||{};appState.agentLog=snapshot;const textEl=byId('agentLogText');const stick=(textEl.scrollTop+textEl.clientHeight)>=(textEl.scrollHeight-16);const text=snapshot.log||'';if(text){textEl.textContent=text;}else if(snapshot.exists){textEl.textContent='日志为空';}else{textEl.textContent='日志文件暂不可读';}let meta=[];if(snapshot.path){meta.push(snapshot.path);}meta.push(formatLogSize(snapshot.size_bytes));if(snapshot.truncated){meta.push('显示最新片段');}if(snapshot.error){meta.push(snapshot.error);}byId('agentLogMeta').textContent=meta.filter(Boolean).join(' · ');if(stick||!appState.agentLogPaused){textEl.scrollTop=textEl.scrollHeight;}}\n"
    "    async function refreshAgentLog(showBanner){if(appState.agentLogPaused&&!showBanner){return;}const btn=byId('refreshAgentLogBtn');if(btn)btn.disabled=true;try{const payload=await request('/api/agent/logs',{method:'GET'});renderAgentLog(payload.agent_log||{});if(showBanner){setBanner('Agent 日志已刷新。',false);}}catch(err){byId('agentLogText').textContent='读取 Agent 日志失败：\\n'+err.message;byId('agentLogMeta').textContent='';if(showBanner){setBanner('刷新 Agent 日志失败。',true);setDetails(err.message);}}finally{if(btn)btn.disabled=false;}}\n"
    "    function toggleAgentLogPause(){appState.agentLogPaused=!appState.agentLogPaused;const btn=byId('pauseAgentLogBtn');if(btn){btn.textContent=appState.agentLogPaused?'继续':'暂停';}if(!appState.agentLogPaused){refreshAgentLog(false);}}\n"
    "    function showOtaLogPanel(){const panel=byId('otaLogPanel');if(panel){panel.style.display='block';}appState.otaLogVisible=true;updateActionDetailsVisibility();}\n"
    "    function otaLogHasNewProgress(snapshot){snapshot=snapshot||{};if(!(snapshot.log||'')){return false;}if(!appState.otaLogPending){return true;}const size=Number(snapshot.size_bytes||0);const start=Number(appState.otaLogStartSize||0);return size>start||size<start;}\n"
    "    function extractOtaExitCode(text){const marker='[config_web] ota update exited rc=';const idx=String(text||'').lastIndexOf(marker);if(idx<0){return null;}const match=String(text||'').slice(idx+marker.length).match(/^(\\d+)/);return match?Number(match[1]):null;}\n"
    "    function applyOtaExitCode(text){const rc=extractOtaExitCode(text);if(rc===null){return;}appState.otaLogPending=false;if(rc!==0){setBanner('OTA 更新失败（rc='+rc+'）。',true);setDetails('最近 OTA 日志：\\n'+String(text||'').slice(-4000),{keepOtaLog:true});}}\n"
    "    function setOtaLogPending(message,startSize){showOtaLogPanel();appState.otaLogPending=true;appState.otaLogStartSize=Number(startSize||0);byId('otaLogText').textContent=message;byId('otaLogMeta').textContent='OTA 更新已启动，等待日志输出';}\n"
    "    function renderOtaLog(snapshot,options){snapshot=snapshot||{};options=options||{};appState.otaLog=snapshot;const textEl=byId('otaLogText');const stick=(textEl.scrollTop+textEl.clientHeight)>=(textEl.scrollHeight-16);const text=snapshot.log||'';if(options.preservePending&&appState.otaLogPending&&!otaLogHasNewProgress(snapshot)){let pendingMeta=[];if(snapshot.path){pendingMeta.push(snapshot.path);}pendingMeta.push('等待 OTA 日志输出');pendingMeta.push(formatLogSize(snapshot.size_bytes));if(snapshot.error){pendingMeta.push(snapshot.error);}byId('otaLogMeta').textContent=pendingMeta.filter(Boolean).join(' · ');return;}if(text){appState.otaLogPending=false;textEl.textContent=text;applyOtaExitCode(text);}else if(snapshot.exists){textEl.textContent='日志为空';}else{textEl.textContent='日志文件暂不可读';}let meta=[];if(snapshot.path){meta.push(snapshot.path);}meta.push(formatLogSize(snapshot.size_bytes));if(snapshot.truncated){meta.push('显示最新片段');}if(snapshot.error){meta.push(snapshot.error);}byId('otaLogMeta').textContent=meta.filter(Boolean).join(' · ');if(stick){textEl.scrollTop=textEl.scrollHeight;}}\n"
    "    function selectOtaLogSnapshot(payload){payload=payload||{};const update=payload.ota_log||{};const health=payload.ota_health_log||{};if(appState.otaLogPending){return update;}if(update.log){return update;}if(health.log){return health;}return update.exists?update:health;}\n"
    "    async function refreshOtaLog(showBanner){if(!appState.otaLogVisible&&!showBanner){return;}if(showBanner){showOtaLogPanel();}const btn=byId('refreshOtaLogBtn');if(btn)btn.disabled=true;try{const payload=await request('/api/ota/logs',{method:'GET'});const snapshot=selectOtaLogSnapshot(payload);renderOtaLog(snapshot, {preservePending:true});const rc=extractOtaExitCode((payload.ota_log||{}).log||'');if(showBanner&&!(rc!==null&&rc!==0)){setBanner('OTA 日志已刷新。',false);}}catch(err){byId('otaLogText').textContent='读取 OTA 日志失败：\\n'+err.message;byId('otaLogMeta').textContent='';if(showBanner){setBanner('刷新 OTA 日志失败。',true);setDetails(err.message,{keepOtaLog:true});}}finally{if(btn)btn.disabled=false;}}\n"
    "    async function triggerOtaUpdate(){const btn=byId('otaUpdateBtn');setOtaLogPending('OTA 更新请求已发送，等待服务端确认...',appState.otaLogStartSize);if(btn)btn.disabled=true;setBanner('OTA 更新已触发。',false);setDetails('',{keepOtaLog:true});try{const payload=await request('/api/ota/update',{method:'POST'});setOtaLogPending('OTA 更新已开始，等待日志输出...',Number(payload.ota_log_start_size_bytes||0));setBanner('OTA 更新已开始。',false);setTimeout(function(){refreshOtaLog(false);},500);}catch(err){appState.otaLogPending=false;byId('otaLogText').textContent='触发 OTA 更新失败：\\n'+err.message;byId('otaLogMeta').textContent='';setBanner('触发 OTA 更新失败。',true);setDetails(err.message,{keepOtaLog:true});}finally{if(btn)btn.disabled=false;}}\n"
    "    function otaHealthText(status){const names={success:'成功',failed:'失败',pending:'等待确认',rolled_back:'已回滚'};return names[status]||status||'';}\n"
    "    function renderFirmwareInfo(fw){fw=fw||{};const versionEl=byId('fwVersion');if(fw.version){versionEl.textContent='\\u56FA\\u4EF6\\u7248\\u672C: '+fw.version;versionEl.style.display='';}else{versionEl.style.display='none';}const healthEl=byId('fwHealth');let parts=[];const status=fw.health_status||'';if(status){parts.push('OTA 状态: '+otaHealthText(status));}if(fw.phase){parts.push('phase: '+fw.phase);}if(fw.running_slot){parts.push('slot '+fw.running_slot);}if(fw.health_error){parts.push('错误: '+fw.health_error);}if(fw.previous_version){parts.push('上一稳定版本: '+fw.previous_version);}healthEl.textContent=parts.join(' · ');healthEl.className='fw-health'+(status==='failed'?' error':'');healthEl.style.display=parts.length?'block':'none';if(status==='failed'){showOtaLogPanel();refreshOtaLog(false);}}\n"
    "    function savedWifiNetworks(){const wifi=appState.wifi||{};if(Array.isArray(wifi.networks))return wifi.networks;if(wifi.ssid)return [{ssid:wifi.ssid,psk:wifi.psk||'',priority:wifi.priority||1}];return [];}\n"
    "    function savedWifiBySsid(ssid){const nets=savedWifiNetworks();for(let i=0;i<nets.length;i++){if(nets[i].ssid===ssid)return nets[i];}return null;}\n"
    "    function connectedWifiSsid(){const status=appState.wifiStatus||{};return status.connected&&status.ssid?status.ssid:'';}\n"
    "    function addWifiName(names,seen,name){if(name&&!seen[name]){seen[name]=true;names.push(name);}}\n"
    "    function displayWifiNames(){const names=[];const seen={};addWifiName(names,seen,connectedWifiSsid());(appState.networks||[]).forEach(function(name){addWifiName(names,seen,name);});savedWifiNetworks().slice().sort(function(a,b){return Number(b.priority||0)-Number(a.priority||0);}).forEach(function(n){addWifiName(names,seen,n.ssid);});return names;}\n"
    "    function visibleWifiNames(names){const connected=connectedWifiSsid();if(!connected||appState.wifiListExpanded)return names;return names.filter(function(name){return name===connected;});}\n"
    "    function toggleWifiListExpanded(){appState.wifiListExpanded=!appState.wifiListExpanded;renderWifiList();}\n"
    "    function appendWifiToggleRow(list,totalCount,visibleCount){if(!connectedWifiSsid()||totalCount<=1)return;const row=document.createElement('div');row.className='wifi-toggle-row';const btn=document.createElement('button');btn.type='button';btn.className='button ghost';btn.textContent=appState.wifiListExpanded?'收起其他 Wi-Fi':'显示其他 Wi-Fi（'+String(totalCount-visibleCount)+'）';btn.onclick=toggleWifiListExpanded;row.appendChild(btn);list.appendChild(row);}\n"
    "    function renderWifiList(){const list=byId('wifiList');list.innerHTML='';const names=displayWifiNames();const visibleNames=visibleWifiNames(names);if(!visibleNames.length){const empty=document.createElement('div');empty.className='wifi-row';const left=document.createElement('div');const title=document.createElement('div');title.className='wifi-main';title.textContent='未扫描到网络';const meta=document.createElement('div');meta.className='wifi-meta';meta.textContent='点“重新扫描”再试一次';left.appendChild(title);left.appendChild(meta);empty.appendChild(left);list.appendChild(empty);return;}const saved=savedWifiNetworks();let maxPriority=0;saved.forEach(function(n){maxPriority=Math.max(maxPriority,Number(n.priority||0));});visibleNames.forEach(function(name){const savedNet=savedWifiBySsid(name);const item=document.createElement('div');let cls='wifi-row';let meta=[];let state='';if(appState.wifiStatus&&appState.wifiStatus.connected&&appState.wifiStatus.ssid===name){cls+=' current';meta.push(appState.wifiStatus.ip_address?('已连接 · '+appState.wifiStatus.ip_address):'已连接');state='✓';}if(savedNet){cls+=' saved';meta.push(Number(savedNet.priority||0)===maxPriority?'已保存 · 最高优先级':'已保存 · 优先级 '+String(savedNet.priority||0));if(!state)state='★';}item.className=cls;const left=document.createElement('button');left.type='button';left.className='wifi-connect';left.onclick=function(){if(savedNet){connectWifi(name,savedNet.psk||'');}else{openWifiModal(name);}};const title=document.createElement('div');title.className='wifi-main';title.textContent=name;left.appendChild(title);if(meta.length){const metaEl=document.createElement('div');metaEl.className='wifi-meta';metaEl.textContent=meta.join(' · ');left.appendChild(metaEl);}const right=document.createElement('div');right.className='wifi-state';right.textContent=state;if(savedNet){const forget=document.createElement('button');forget.type='button';forget.className='button ghost';forget.textContent='忘记';forget.onclick=function(event){event.stopPropagation();forgetWifi(name);};right.appendChild(forget);}item.appendChild(left);item.appendChild(right);list.appendChild(item);});appendWifiToggleRow(list,names.length,visibleNames.length);}\n"
    "    function applyPayload(payload){appState.config=payload.config||{};appState.wifi=payload.wifi||{};appState.wifiStatus=payload.wifi_status||{};appState.systemEnv=payload.system_env||'';byId('system_env_content').value=appState.systemEnv;renderAgentStatus(payload.agent_status||{});fillConfigForm(appState.config);lockAllSections();renderFirmwareInfo(payload.firmware||{});}\n"
    "    async function loadConfig(){const payload=await request('/api/config',{method:'GET'});applyPayload(payload);if(payload.config_error||payload.wifi_error){setDetails([payload.config_error||'',payload.wifi_error||''].filter(Boolean).join('\\n'));}return payload;}\n"
    "    async function scanWifi(showBanner){byId('scanBtn').disabled=true;try{const payload=await request('/api/wifi/scan',{method:'POST'});appState.networks=payload.networks||[];renderWifiList();if(showBanner!==false){setBanner('Wi-Fi 列表已刷新。',false);setDetails('');}}catch(err){setBanner('扫描 Wi-Fi 失败。',true);setDetails(err.message);}finally{byId('scanBtn').disabled=false;}}\n"
    "    async function reloadAll(){byId('reloadBtn').disabled=true;try{await loadConfig();await scanWifi(false);setBanner('已刷新配置和 Wi-Fi 列表。',false);}catch(err){setBanner('刷新失败。',true);setDetails(err.message);}finally{byId('reloadBtn').disabled=false;}}\n"
    "    function openWifiModal(ssid){const saved=savedWifiBySsid(ssid);appState.selectedSsid=ssid;byId('wifiModalText').textContent='连接到 “'+ssid+'”';byId('wifiPasswordInput').value=saved&&saved.psk?saved.psk:'';byId('wifiModal').classList.add('show');byId('wifiPasswordInput').focus();}\n"
    "    function closeWifiModal(){byId('wifiModal').classList.remove('show');appState.selectedSsid='';}\n"
    "    async function connectWifi(ssid,psk){const btn=byId('connectWifiBtn');if(btn)btn.disabled=true;try{const payload=await request('/api/wifi/connect',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ssid:ssid,psk:psk})});appState.wifi=payload.wifi||{ssid:ssid,psk:psk};appState.wifiStatus=payload.wifi_status||{};if(payload.ok&&connectedWifiSsid()){appState.wifiListExpanded=false;}renderWifiList();closeWifiModal();setBanner('已尝试连接 “'+ssid+'”。',!payload.ok);setDetails(payload.ok?'':(payload.wifi_apply&&payload.wifi_apply.output?payload.wifi_apply.output:''));}catch(err){setBanner('连接 Wi-Fi 失败。',true);setDetails(err.message);}finally{if(btn)btn.disabled=false;}}\n"
    "    function connectSelectedWifi(){return connectWifi(appState.selectedSsid,byId('wifiPasswordInput').value);}\n"
    "    async function forgetWifi(ssid){if(!window.confirm('忘记 “'+ssid+'”？'))return;try{const payload=await request('/api/wifi/forget',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ssid:ssid})});appState.wifi=payload.wifi||{};appState.wifiStatus=payload.wifi_status||{};renderWifiList();setBanner('已忘记 “'+ssid+'”。',false);setDetails(payload.wifi_apply&&payload.wifi_apply.output?payload.wifi_apply.output:'');}catch(err){setBanner('忘记 Wi-Fi 失败。',true);setDetails(err.message);}}\n"
    "    async function poweroffDevice(){setBanner('正在关机...',false);setDetails('已发送 poweroff 请求，设备会关机；由于仍有供电，板子随后会自动重新上电。');try{await request('/api/poweroff',{method:'POST'});setDetails('poweroff 指令已下发。请等待 USB 断开并自动重新枚举后再刷新页面。');}catch(err){setBanner('关机失败。',true);setDetails(err.message);}}\n"
    "    async function saveSection(section){if(!appState.config){return;}if(sectionModeLocked(section)){setBanner('['+section+'] 仅在 agent.input_mode = stt 时可保存。',false);setDetails('先在 [agent] 中把 input_mode 改为 stt 并保存。');return;}byId('save-'+section).disabled=true;try{appState.config[section]=readSection(section);const payload=await request('/api/config',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({config:appState.config,apply_wifi:false})});if(payload.config){appState.config=payload.config;}fillConfigForm(appState.config);delete sectionSnapshots[section];setSectionLocked(section,true);byId('section-'+section).classList.remove('editing');if(payload.reboot_required){setBanner('['+section+'] 已保存。pointer_mode 需要关机重启后生效。',false);setDetails('不会热重启 USB HID 或 Agent，避免触发 USB gadget 内核异常。');if(window.confirm('pointer_mode 已保存，需要关机重启后生效。现在执行 poweroff 吗？')){await poweroffDevice();}else{setDetails('已取消立即关机。请稍后手动执行 poweroff，或重新上电后验证 Android 枚举结果。');}}else{setBanner('['+section+'] 已保存。',false);setDetails('');setTimeout(function(){refreshAgentStatus(false);},1200);}}catch(err){setBanner('保存 ['+section+'] 失败。',true);setDetails(err.message);setSectionLocked(section,false);}finally{byId('save-'+section).disabled=false;}}\n"
    "    async function saveSystemEnv(){byId('save-system_env').disabled=true;try{const payload=await request('/api/system/env',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({system_env:byId('system_env_content').value})});appState.systemEnv=payload.system_env||byId('system_env_content').value;byId('system_env_content').value=appState.systemEnv;setSystemEnvLocked(true);byId('section-system_env').classList.remove('editing');setBanner('env 已保存。',false);setDetails('');setTimeout(function(){refreshAgentStatus(false);},1200);}catch(err){setBanner('保存 env 失败。',true);setDetails(err.message);setSystemEnvLocked(false);}finally{byId('save-system_env').disabled=false;}}\n"
    "    function closeTestToast(){byId('testToast').classList.remove('show','pass','fail');}\n"
    "    async function testSection(section){if(sectionModeLocked(section)){setBanner('['+section+'] 仅在 agent.input_mode = stt 时可测试。',false);setDetails('先在 [agent] 中把 input_mode 改为 stt 并保存。');return;}var toast=byId('testToast');toast.className='test-toast show';byId('testToastTitle').textContent='正在测试 ['+section+'] ...';byId('testToastBody').textContent='';try{const values=readSection(section);const payload=await request('/api/config/test',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({section:section,values:values})});const results=payload.results||[];let detail='';results.forEach(function(r){detail+=(r.passed?'\\u2705':'\\u274C')+' '+r.check+': '+r.detail+'\\n';});toast.className='test-toast show '+(payload.ok?'pass':'fail');byId('testToastTitle').textContent=payload.ok?'['+section+'] 测试通过':'['+section+'] 测试未通过';byId('testToastBody').textContent=detail;}catch(err){toast.className='test-toast show fail';byId('testToastTitle').textContent='测试 ['+section+'] 失败';byId('testToastBody').textContent=err.message;}}\n"
    "    window.addEventListener('click',function(event){if(event.target===byId('wifiModal')){closeWifiModal();}});\n"
    "    async function loadConfigMeta(){const meta=await request('/api/config/meta',{method:'GET'});buildConfigMeta(meta);}\n"
    "    function disableAgentConfigEditing(){document.querySelectorAll('.section-card').forEach(function(card){if(card.id==='section-system_env')return;card.classList.remove('editing');card.querySelectorAll('button,input,select,textarea').forEach(function(el){el.disabled=true;});});}\n"
    "    function initialReadyMessage(metaOk){if(!metaOk)return '读取配置元数据失败：agent.toml 编辑已禁用，Wi-Fi 与日志仍可正常使用。';if(connectedWifiSsid())return 'Wi-Fi 已连接。';return '请选择 Wi-Fi，或按分组编辑 agent.toml。';}\n"
    "    (async function init(){let metaOk=true;setBanner('正在读取配置元数据...',false);try{await loadConfigMeta();}catch(err){metaOk=false;setDetails(err.message);}if(metaOk){hydrateSelectOptions();bindFieldVisibility();}lockAllSections();setBanner('正在读取配置...',false);try{if(metaOk){await loadConfig();}await scanWifi(false);await refreshAgentLog(false);setBanner(initialReadyMessage(metaOk),!metaOk);}catch(err){setBanner('页面初始化失败。',true);setDetails(err.message);}if(!metaOk){disableAgentConfigEditing();}setInterval(function(){refreshAgentStatus(false);},5000);setInterval(function(){refreshAgentLog(false);},2000);setInterval(function(){refreshOtaLog(false);},2000);})();\n"
    "  </script>\n"
    "</body>\n"
    "</html>\n";
